// Code generated by ent, DO NOT EDIT.

package signingrequest

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the signingrequest type in the database.
	Label = "signing_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldUpdateBy holds the string denoting the update_by field in the database.
	FieldUpdateBy = "update_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldTemplateID holds the string denoting the template_id field in the database.
	FieldTemplateID = "template_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSigningType holds the string denoting the signing_type field in the database.
	FieldSigningType = "signing_type"
	// FieldOriginalFileKey holds the string denoting the original_file_key field in the database.
	FieldOriginalFileKey = "original_file_key"
	// FieldSignedFileKey holds the string denoting the signed_file_key field in the database.
	FieldSignedFileKey = "signed_file_key"
	// FieldFieldValues holds the string denoting the field_values field in the database.
	FieldFieldValues = "field_values"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeRecipients holds the string denoting the recipients edge name in mutations.
	EdgeRecipients = "recipients"
	// Table holds the table name of the signingrequest in the database.
	Table = "paperless_signing_requests"
	// RecipientsTable is the table that holds the recipients relation/edge.
	RecipientsTable = "paperless_signing_recipients"
	// RecipientsInverseTable is the table name for the SigningRecipient entity.
	// It exists in this package in order to avoid circular dependency with the "signingrecipient" package.
	RecipientsInverseTable = "paperless_signing_recipients"
	// RecipientsColumn is the table column denoting the recipients relation/edge.
	RecipientsColumn = "signing_request_id"
)

// Columns holds all SQL columns for signingrequest fields.
var Columns = []string{
	FieldID,
	FieldCreateBy,
	FieldUpdateBy,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTenantID,
	FieldTemplateID,
	FieldName,
	FieldStatus,
	FieldSigningType,
	FieldOriginalFileKey,
	FieldSignedFileKey,
	FieldFieldValues,
	FieldMessage,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/go-tangra/go-tangra-paperless/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// TemplateIDValidator is a validator for the "template_id" field. It is called by the builders before save.
	TemplateIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// OriginalFileKeyValidator is a validator for the "original_file_key" field. It is called by the builders before save.
	OriginalFileKeyValidator func(string) error
	// SignedFileKeyValidator is a validator for the "signed_file_key" field. It is called by the builders before save.
	SignedFileKeyValidator func(string) error
	// MessageValidator is a validator for the "message" field. It is called by the builders before save.
	MessageValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusSIGNING_REQUEST_STATUS_DRAFT is the default value of the Status enum.
const DefaultStatus = StatusSIGNING_REQUEST_STATUS_DRAFT

// Status values.
const (
	StatusSIGNING_REQUEST_STATUS_UNSPECIFIED Status = "SIGNING_REQUEST_STATUS_UNSPECIFIED"
	StatusSIGNING_REQUEST_STATUS_DRAFT       Status = "SIGNING_REQUEST_STATUS_DRAFT"
	StatusSIGNING_REQUEST_STATUS_PENDING     Status = "SIGNING_REQUEST_STATUS_PENDING"
	StatusSIGNING_REQUEST_STATUS_COMPLETED   Status = "SIGNING_REQUEST_STATUS_COMPLETED"
	StatusSIGNING_REQUEST_STATUS_CANCELLED   Status = "SIGNING_REQUEST_STATUS_CANCELLED"
	StatusSIGNING_REQUEST_STATUS_EXPIRED     Status = "SIGNING_REQUEST_STATUS_EXPIRED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusSIGNING_REQUEST_STATUS_UNSPECIFIED, StatusSIGNING_REQUEST_STATUS_DRAFT, StatusSIGNING_REQUEST_STATUS_PENDING, StatusSIGNING_REQUEST_STATUS_COMPLETED, StatusSIGNING_REQUEST_STATUS_CANCELLED, StatusSIGNING_REQUEST_STATUS_EXPIRED:
		return nil
	default:
		return fmt.Errorf("signingrequest: invalid enum value for status field: %q", s)
	}
}

// SigningType defines the type for the "signing_type" enum field.
type SigningType string

// SigningTypeSIGNING_REQUEST_TYPE_EXTERNAL is the default value of the SigningType enum.
const DefaultSigningType = SigningTypeSIGNING_REQUEST_TYPE_EXTERNAL

// SigningType values.
const (
	SigningTypeSIGNING_REQUEST_TYPE_UNSPECIFIED SigningType = "SIGNING_REQUEST_TYPE_UNSPECIFIED"
	SigningTypeSIGNING_REQUEST_TYPE_EXTERNAL    SigningType = "SIGNING_REQUEST_TYPE_EXTERNAL"
	SigningTypeSIGNING_REQUEST_TYPE_INTERNAL    SigningType = "SIGNING_REQUEST_TYPE_INTERNAL"
)

func (st SigningType) String() string {
	return string(st)
}

// SigningTypeValidator is a validator for the "signing_type" field enum values. It is called by the builders before save.
func SigningTypeValidator(st SigningType) error {
	switch st {
	case SigningTypeSIGNING_REQUEST_TYPE_UNSPECIFIED, SigningTypeSIGNING_REQUEST_TYPE_EXTERNAL, SigningTypeSIGNING_REQUEST_TYPE_INTERNAL:
		return nil
	default:
		return fmt.Errorf("signingrequest: invalid enum value for signing_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the SigningRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByUpdateBy orders the results by the update_by field.
func ByUpdateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByTemplateID orders the results by the template_id field.
func ByTemplateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySigningType orders the results by the signing_type field.
func BySigningType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSigningType, opts...).ToFunc()
}

// ByOriginalFileKey orders the results by the original_file_key field.
func ByOriginalFileKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalFileKey, opts...).ToFunc()
}

// BySignedFileKey orders the results by the signed_file_key field.
func BySignedFileKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignedFileKey, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByRecipientsCount orders the results by recipients count.
func ByRecipientsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRecipientsStep(), opts...)
	}
}

// ByRecipients orders the results by recipients terms.
func ByRecipients(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecipientsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRecipientsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecipientsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RecipientsTable, RecipientsColumn),
	)
}
