// Code generated by ent, DO NOT EDIT.

package signingrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldCreateBy, v))
}

// UpdateBy applies equality check predicate on the "update_by" field. It's identical to UpdateByEQ.
func UpdateBy(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldUpdateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldTenantID, v))
}

// TemplateID applies equality check predicate on the "template_id" field. It's identical to TemplateIDEQ.
func TemplateID(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldTemplateID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldName, v))
}

// OriginalFileKey applies equality check predicate on the "original_file_key" field. It's identical to OriginalFileKeyEQ.
func OriginalFileKey(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldOriginalFileKey, v))
}

// SignedFileKey applies equality check predicate on the "signed_file_key" field. It's identical to SignedFileKeyEQ.
func SignedFileKey(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldSignedFileKey, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldMessage, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldExpiresAt, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotNull(FieldCreateBy))
}

// UpdateByEQ applies the EQ predicate on the "update_by" field.
func UpdateByEQ(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldUpdateBy, v))
}

// UpdateByNEQ applies the NEQ predicate on the "update_by" field.
func UpdateByNEQ(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldUpdateBy, v))
}

// UpdateByIn applies the In predicate on the "update_by" field.
func UpdateByIn(vs ...uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldUpdateBy, vs...))
}

// UpdateByNotIn applies the NotIn predicate on the "update_by" field.
func UpdateByNotIn(vs ...uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldUpdateBy, vs...))
}

// UpdateByGT applies the GT predicate on the "update_by" field.
func UpdateByGT(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldUpdateBy, v))
}

// UpdateByGTE applies the GTE predicate on the "update_by" field.
func UpdateByGTE(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldUpdateBy, v))
}

// UpdateByLT applies the LT predicate on the "update_by" field.
func UpdateByLT(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldUpdateBy, v))
}

// UpdateByLTE applies the LTE predicate on the "update_by" field.
func UpdateByLTE(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldUpdateBy, v))
}

// UpdateByIsNil applies the IsNil predicate on the "update_by" field.
func UpdateByIsNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIsNull(FieldUpdateBy))
}

// UpdateByNotNil applies the NotNil predicate on the "update_by" field.
func UpdateByNotNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotNull(FieldUpdateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotNull(FieldTenantID))
}

// TemplateIDEQ applies the EQ predicate on the "template_id" field.
func TemplateIDEQ(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldTemplateID, v))
}

// TemplateIDNEQ applies the NEQ predicate on the "template_id" field.
func TemplateIDNEQ(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldTemplateID, v))
}

// TemplateIDIn applies the In predicate on the "template_id" field.
func TemplateIDIn(vs ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldTemplateID, vs...))
}

// TemplateIDNotIn applies the NotIn predicate on the "template_id" field.
func TemplateIDNotIn(vs ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldTemplateID, vs...))
}

// TemplateIDGT applies the GT predicate on the "template_id" field.
func TemplateIDGT(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldTemplateID, v))
}

// TemplateIDGTE applies the GTE predicate on the "template_id" field.
func TemplateIDGTE(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldTemplateID, v))
}

// TemplateIDLT applies the LT predicate on the "template_id" field.
func TemplateIDLT(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldTemplateID, v))
}

// TemplateIDLTE applies the LTE predicate on the "template_id" field.
func TemplateIDLTE(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldTemplateID, v))
}

// TemplateIDContains applies the Contains predicate on the "template_id" field.
func TemplateIDContains(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldContains(FieldTemplateID, v))
}

// TemplateIDHasPrefix applies the HasPrefix predicate on the "template_id" field.
func TemplateIDHasPrefix(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldHasPrefix(FieldTemplateID, v))
}

// TemplateIDHasSuffix applies the HasSuffix predicate on the "template_id" field.
func TemplateIDHasSuffix(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldHasSuffix(FieldTemplateID, v))
}

// TemplateIDEqualFold applies the EqualFold predicate on the "template_id" field.
func TemplateIDEqualFold(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEqualFold(FieldTemplateID, v))
}

// TemplateIDContainsFold applies the ContainsFold predicate on the "template_id" field.
func TemplateIDContainsFold(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldContainsFold(FieldTemplateID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// SigningTypeEQ applies the EQ predicate on the "signing_type" field.
func SigningTypeEQ(v SigningType) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldSigningType, v))
}

// SigningTypeNEQ applies the NEQ predicate on the "signing_type" field.
func SigningTypeNEQ(v SigningType) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldSigningType, v))
}

// SigningTypeIn applies the In predicate on the "signing_type" field.
func SigningTypeIn(vs ...SigningType) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldSigningType, vs...))
}

// SigningTypeNotIn applies the NotIn predicate on the "signing_type" field.
func SigningTypeNotIn(vs ...SigningType) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldSigningType, vs...))
}

// OriginalFileKeyEQ applies the EQ predicate on the "original_file_key" field.
func OriginalFileKeyEQ(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldOriginalFileKey, v))
}

// OriginalFileKeyNEQ applies the NEQ predicate on the "original_file_key" field.
func OriginalFileKeyNEQ(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldOriginalFileKey, v))
}

// OriginalFileKeyIn applies the In predicate on the "original_file_key" field.
func OriginalFileKeyIn(vs ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldOriginalFileKey, vs...))
}

// OriginalFileKeyNotIn applies the NotIn predicate on the "original_file_key" field.
func OriginalFileKeyNotIn(vs ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldOriginalFileKey, vs...))
}

// OriginalFileKeyGT applies the GT predicate on the "original_file_key" field.
func OriginalFileKeyGT(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldOriginalFileKey, v))
}

// OriginalFileKeyGTE applies the GTE predicate on the "original_file_key" field.
func OriginalFileKeyGTE(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldOriginalFileKey, v))
}

// OriginalFileKeyLT applies the LT predicate on the "original_file_key" field.
func OriginalFileKeyLT(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldOriginalFileKey, v))
}

// OriginalFileKeyLTE applies the LTE predicate on the "original_file_key" field.
func OriginalFileKeyLTE(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldOriginalFileKey, v))
}

// OriginalFileKeyContains applies the Contains predicate on the "original_file_key" field.
func OriginalFileKeyContains(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldContains(FieldOriginalFileKey, v))
}

// OriginalFileKeyHasPrefix applies the HasPrefix predicate on the "original_file_key" field.
func OriginalFileKeyHasPrefix(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldHasPrefix(FieldOriginalFileKey, v))
}

// OriginalFileKeyHasSuffix applies the HasSuffix predicate on the "original_file_key" field.
func OriginalFileKeyHasSuffix(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldHasSuffix(FieldOriginalFileKey, v))
}

// OriginalFileKeyIsNil applies the IsNil predicate on the "original_file_key" field.
func OriginalFileKeyIsNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIsNull(FieldOriginalFileKey))
}

// OriginalFileKeyNotNil applies the NotNil predicate on the "original_file_key" field.
func OriginalFileKeyNotNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotNull(FieldOriginalFileKey))
}

// OriginalFileKeyEqualFold applies the EqualFold predicate on the "original_file_key" field.
func OriginalFileKeyEqualFold(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEqualFold(FieldOriginalFileKey, v))
}

// OriginalFileKeyContainsFold applies the ContainsFold predicate on the "original_file_key" field.
func OriginalFileKeyContainsFold(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldContainsFold(FieldOriginalFileKey, v))
}

// SignedFileKeyEQ applies the EQ predicate on the "signed_file_key" field.
func SignedFileKeyEQ(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldSignedFileKey, v))
}

// SignedFileKeyNEQ applies the NEQ predicate on the "signed_file_key" field.
func SignedFileKeyNEQ(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldSignedFileKey, v))
}

// SignedFileKeyIn applies the In predicate on the "signed_file_key" field.
func SignedFileKeyIn(vs ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldSignedFileKey, vs...))
}

// SignedFileKeyNotIn applies the NotIn predicate on the "signed_file_key" field.
func SignedFileKeyNotIn(vs ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldSignedFileKey, vs...))
}

// SignedFileKeyGT applies the GT predicate on the "signed_file_key" field.
func SignedFileKeyGT(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldSignedFileKey, v))
}

// SignedFileKeyGTE applies the GTE predicate on the "signed_file_key" field.
func SignedFileKeyGTE(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldSignedFileKey, v))
}

// SignedFileKeyLT applies the LT predicate on the "signed_file_key" field.
func SignedFileKeyLT(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldSignedFileKey, v))
}

// SignedFileKeyLTE applies the LTE predicate on the "signed_file_key" field.
func SignedFileKeyLTE(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldSignedFileKey, v))
}

// SignedFileKeyContains applies the Contains predicate on the "signed_file_key" field.
func SignedFileKeyContains(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldContains(FieldSignedFileKey, v))
}

// SignedFileKeyHasPrefix applies the HasPrefix predicate on the "signed_file_key" field.
func SignedFileKeyHasPrefix(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldHasPrefix(FieldSignedFileKey, v))
}

// SignedFileKeyHasSuffix applies the HasSuffix predicate on the "signed_file_key" field.
func SignedFileKeyHasSuffix(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldHasSuffix(FieldSignedFileKey, v))
}

// SignedFileKeyIsNil applies the IsNil predicate on the "signed_file_key" field.
func SignedFileKeyIsNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIsNull(FieldSignedFileKey))
}

// SignedFileKeyNotNil applies the NotNil predicate on the "signed_file_key" field.
func SignedFileKeyNotNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotNull(FieldSignedFileKey))
}

// SignedFileKeyEqualFold applies the EqualFold predicate on the "signed_file_key" field.
func SignedFileKeyEqualFold(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEqualFold(FieldSignedFileKey, v))
}

// SignedFileKeyContainsFold applies the ContainsFold predicate on the "signed_file_key" field.
func SignedFileKeyContainsFold(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldContainsFold(FieldSignedFileKey, v))
}

// FieldValuesIsNil applies the IsNil predicate on the "field_values" field.
func FieldValuesIsNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIsNull(FieldFieldValues))
}

// FieldValuesNotNil applies the NotNil predicate on the "field_values" field.
func FieldValuesNotNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotNull(FieldFieldValues))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldContainsFold(FieldMessage, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.SigningRequest {
	return predicate.SigningRequest(sql.FieldNotNull(FieldExpiresAt))
}

// HasRecipients applies the HasEdge predicate on the "recipients" edge.
func HasRecipients() predicate.SigningRequest {
	return predicate.SigningRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecipientsTable, RecipientsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecipientsWith applies the HasEdge predicate on the "recipients" edge with a given conditions (other predicates).
func HasRecipientsWith(preds ...predicate.SigningRecipient) predicate.SigningRequest {
	return predicate.SigningRequest(func(s *sql.Selector) {
		step := newRecipientsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SigningRequest) predicate.SigningRequest {
	return predicate.SigningRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SigningRequest) predicate.SigningRequest {
	return predicate.SigningRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SigningRequest) predicate.SigningRequest {
	return predicate.SigningRequest(sql.NotPredicates(p))
}
