// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/auditlog"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/category"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/document"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/documentpermission"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingrecipient"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingrequest"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingtemplate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 7)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   auditlog.Table,
			Columns: auditlog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: auditlog.FieldID,
			},
		},
		Type: "AuditLog",
		Fields: map[string]*sqlgraph.FieldSpec{
			auditlog.FieldCreateTime:         {Type: field.TypeTime, Column: auditlog.FieldCreateTime},
			auditlog.FieldUpdateTime:         {Type: field.TypeTime, Column: auditlog.FieldUpdateTime},
			auditlog.FieldDeleteTime:         {Type: field.TypeTime, Column: auditlog.FieldDeleteTime},
			auditlog.FieldTenantID:           {Type: field.TypeUint32, Column: auditlog.FieldTenantID},
			auditlog.FieldAuditID:            {Type: field.TypeString, Column: auditlog.FieldAuditID},
			auditlog.FieldRequestID:          {Type: field.TypeString, Column: auditlog.FieldRequestID},
			auditlog.FieldOperation:          {Type: field.TypeString, Column: auditlog.FieldOperation},
			auditlog.FieldServiceName:        {Type: field.TypeString, Column: auditlog.FieldServiceName},
			auditlog.FieldClientID:           {Type: field.TypeString, Column: auditlog.FieldClientID},
			auditlog.FieldClientCommonName:   {Type: field.TypeString, Column: auditlog.FieldClientCommonName},
			auditlog.FieldClientOrganization: {Type: field.TypeString, Column: auditlog.FieldClientOrganization},
			auditlog.FieldClientSerialNumber: {Type: field.TypeString, Column: auditlog.FieldClientSerialNumber},
			auditlog.FieldIsAuthenticated:    {Type: field.TypeBool, Column: auditlog.FieldIsAuthenticated},
			auditlog.FieldSuccess:            {Type: field.TypeBool, Column: auditlog.FieldSuccess},
			auditlog.FieldErrorCode:          {Type: field.TypeInt32, Column: auditlog.FieldErrorCode},
			auditlog.FieldErrorMessage:       {Type: field.TypeString, Column: auditlog.FieldErrorMessage},
			auditlog.FieldLatencyMs:          {Type: field.TypeInt64, Column: auditlog.FieldLatencyMs},
			auditlog.FieldPeerAddress:        {Type: field.TypeString, Column: auditlog.FieldPeerAddress},
			auditlog.FieldGeoLocation:        {Type: field.TypeJSON, Column: auditlog.FieldGeoLocation},
			auditlog.FieldLogHash:            {Type: field.TypeString, Column: auditlog.FieldLogHash},
			auditlog.FieldSignature:          {Type: field.TypeBytes, Column: auditlog.FieldSignature},
			auditlog.FieldMetadata:           {Type: field.TypeJSON, Column: auditlog.FieldMetadata},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   category.Table,
			Columns: category.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: category.FieldID,
			},
		},
		Type: "Category",
		Fields: map[string]*sqlgraph.FieldSpec{
			category.FieldCreateBy:    {Type: field.TypeUint32, Column: category.FieldCreateBy},
			category.FieldCreateTime:  {Type: field.TypeTime, Column: category.FieldCreateTime},
			category.FieldUpdateTime:  {Type: field.TypeTime, Column: category.FieldUpdateTime},
			category.FieldDeleteTime:  {Type: field.TypeTime, Column: category.FieldDeleteTime},
			category.FieldTenantID:    {Type: field.TypeUint32, Column: category.FieldTenantID},
			category.FieldParentID:    {Type: field.TypeString, Column: category.FieldParentID},
			category.FieldName:        {Type: field.TypeString, Column: category.FieldName},
			category.FieldPath:        {Type: field.TypeString, Column: category.FieldPath},
			category.FieldDescription: {Type: field.TypeString, Column: category.FieldDescription},
			category.FieldDepth:       {Type: field.TypeInt32, Column: category.FieldDepth},
			category.FieldSortOrder:   {Type: field.TypeInt32, Column: category.FieldSortOrder},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   document.Table,
			Columns: document.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: document.FieldID,
			},
		},
		Type: "Document",
		Fields: map[string]*sqlgraph.FieldSpec{
			document.FieldCreateBy:          {Type: field.TypeUint32, Column: document.FieldCreateBy},
			document.FieldUpdateBy:          {Type: field.TypeUint32, Column: document.FieldUpdateBy},
			document.FieldCreateTime:        {Type: field.TypeTime, Column: document.FieldCreateTime},
			document.FieldUpdateTime:        {Type: field.TypeTime, Column: document.FieldUpdateTime},
			document.FieldDeleteTime:        {Type: field.TypeTime, Column: document.FieldDeleteTime},
			document.FieldTenantID:          {Type: field.TypeUint32, Column: document.FieldTenantID},
			document.FieldCategoryID:        {Type: field.TypeString, Column: document.FieldCategoryID},
			document.FieldName:              {Type: field.TypeString, Column: document.FieldName},
			document.FieldDescription:       {Type: field.TypeString, Column: document.FieldDescription},
			document.FieldFileKey:           {Type: field.TypeString, Column: document.FieldFileKey},
			document.FieldFileName:          {Type: field.TypeString, Column: document.FieldFileName},
			document.FieldFileSize:          {Type: field.TypeInt64, Column: document.FieldFileSize},
			document.FieldMimeType:          {Type: field.TypeString, Column: document.FieldMimeType},
			document.FieldChecksum:          {Type: field.TypeString, Column: document.FieldChecksum},
			document.FieldTags:              {Type: field.TypeJSON, Column: document.FieldTags},
			document.FieldStatus:            {Type: field.TypeEnum, Column: document.FieldStatus},
			document.FieldSource:            {Type: field.TypeEnum, Column: document.FieldSource},
			document.FieldContentText:       {Type: field.TypeString, Column: document.FieldContentText},
			document.FieldExtractedMetadata: {Type: field.TypeJSON, Column: document.FieldExtractedMetadata},
			document.FieldProcessingStatus:  {Type: field.TypeEnum, Column: document.FieldProcessingStatus},
		},
	}
	graph.Nodes[3] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   documentpermission.Table,
			Columns: documentpermission.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: documentpermission.FieldID,
			},
		},
		Type: "DocumentPermission",
		Fields: map[string]*sqlgraph.FieldSpec{
			documentpermission.FieldCreateTime:   {Type: field.TypeTime, Column: documentpermission.FieldCreateTime},
			documentpermission.FieldUpdateTime:   {Type: field.TypeTime, Column: documentpermission.FieldUpdateTime},
			documentpermission.FieldDeleteTime:   {Type: field.TypeTime, Column: documentpermission.FieldDeleteTime},
			documentpermission.FieldTenantID:     {Type: field.TypeUint32, Column: documentpermission.FieldTenantID},
			documentpermission.FieldResourceType: {Type: field.TypeEnum, Column: documentpermission.FieldResourceType},
			documentpermission.FieldResourceID:   {Type: field.TypeString, Column: documentpermission.FieldResourceID},
			documentpermission.FieldRelation:     {Type: field.TypeEnum, Column: documentpermission.FieldRelation},
			documentpermission.FieldSubjectType:  {Type: field.TypeEnum, Column: documentpermission.FieldSubjectType},
			documentpermission.FieldSubjectID:    {Type: field.TypeString, Column: documentpermission.FieldSubjectID},
			documentpermission.FieldGrantedBy:    {Type: field.TypeUint32, Column: documentpermission.FieldGrantedBy},
			documentpermission.FieldExpiresAt:    {Type: field.TypeTime, Column: documentpermission.FieldExpiresAt},
		},
	}
	graph.Nodes[4] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   signingrecipient.Table,
			Columns: signingrecipient.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: signingrecipient.FieldID,
			},
		},
		Type: "SigningRecipient",
		Fields: map[string]*sqlgraph.FieldSpec{
			signingrecipient.FieldCreateTime:       {Type: field.TypeTime, Column: signingrecipient.FieldCreateTime},
			signingrecipient.FieldUpdateTime:       {Type: field.TypeTime, Column: signingrecipient.FieldUpdateTime},
			signingrecipient.FieldDeleteTime:       {Type: field.TypeTime, Column: signingrecipient.FieldDeleteTime},
			signingrecipient.FieldSigningRequestID: {Type: field.TypeString, Column: signingrecipient.FieldSigningRequestID},
			signingrecipient.FieldEmail:            {Type: field.TypeString, Column: signingrecipient.FieldEmail},
			signingrecipient.FieldName:             {Type: field.TypeString, Column: signingrecipient.FieldName},
			signingrecipient.FieldUserID:           {Type: field.TypeUint32, Column: signingrecipient.FieldUserID},
			signingrecipient.FieldSigningOrder:     {Type: field.TypeInt32, Column: signingrecipient.FieldSigningOrder},
			signingrecipient.FieldStatus:           {Type: field.TypeEnum, Column: signingrecipient.FieldStatus},
			signingrecipient.FieldToken:            {Type: field.TypeString, Column: signingrecipient.FieldToken},
			signingrecipient.FieldSignedAt:         {Type: field.TypeTime, Column: signingrecipient.FieldSignedAt},
			signingrecipient.FieldSignedIP:         {Type: field.TypeString, Column: signingrecipient.FieldSignedIP},
			signingrecipient.FieldSignatureData:    {Type: field.TypeBytes, Column: signingrecipient.FieldSignatureData},
		},
	}
	graph.Nodes[5] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   signingrequest.Table,
			Columns: signingrequest.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: signingrequest.FieldID,
			},
		},
		Type: "SigningRequest",
		Fields: map[string]*sqlgraph.FieldSpec{
			signingrequest.FieldCreateBy:        {Type: field.TypeUint32, Column: signingrequest.FieldCreateBy},
			signingrequest.FieldUpdateBy:        {Type: field.TypeUint32, Column: signingrequest.FieldUpdateBy},
			signingrequest.FieldCreateTime:      {Type: field.TypeTime, Column: signingrequest.FieldCreateTime},
			signingrequest.FieldUpdateTime:      {Type: field.TypeTime, Column: signingrequest.FieldUpdateTime},
			signingrequest.FieldDeleteTime:      {Type: field.TypeTime, Column: signingrequest.FieldDeleteTime},
			signingrequest.FieldTenantID:        {Type: field.TypeUint32, Column: signingrequest.FieldTenantID},
			signingrequest.FieldTemplateID:      {Type: field.TypeString, Column: signingrequest.FieldTemplateID},
			signingrequest.FieldName:            {Type: field.TypeString, Column: signingrequest.FieldName},
			signingrequest.FieldStatus:          {Type: field.TypeEnum, Column: signingrequest.FieldStatus},
			signingrequest.FieldSigningType:     {Type: field.TypeEnum, Column: signingrequest.FieldSigningType},
			signingrequest.FieldOriginalFileKey: {Type: field.TypeString, Column: signingrequest.FieldOriginalFileKey},
			signingrequest.FieldSignedFileKey:   {Type: field.TypeString, Column: signingrequest.FieldSignedFileKey},
			signingrequest.FieldFieldValues:     {Type: field.TypeJSON, Column: signingrequest.FieldFieldValues},
			signingrequest.FieldMessage:         {Type: field.TypeString, Column: signingrequest.FieldMessage},
			signingrequest.FieldExpiresAt:       {Type: field.TypeTime, Column: signingrequest.FieldExpiresAt},
		},
	}
	graph.Nodes[6] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   signingtemplate.Table,
			Columns: signingtemplate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: signingtemplate.FieldID,
			},
		},
		Type: "SigningTemplate",
		Fields: map[string]*sqlgraph.FieldSpec{
			signingtemplate.FieldCreateBy:            {Type: field.TypeUint32, Column: signingtemplate.FieldCreateBy},
			signingtemplate.FieldUpdateBy:            {Type: field.TypeUint32, Column: signingtemplate.FieldUpdateBy},
			signingtemplate.FieldCreateTime:          {Type: field.TypeTime, Column: signingtemplate.FieldCreateTime},
			signingtemplate.FieldUpdateTime:          {Type: field.TypeTime, Column: signingtemplate.FieldUpdateTime},
			signingtemplate.FieldDeleteTime:          {Type: field.TypeTime, Column: signingtemplate.FieldDeleteTime},
			signingtemplate.FieldTenantID:            {Type: field.TypeUint32, Column: signingtemplate.FieldTenantID},
			signingtemplate.FieldName:                {Type: field.TypeString, Column: signingtemplate.FieldName},
			signingtemplate.FieldDescription:         {Type: field.TypeString, Column: signingtemplate.FieldDescription},
			signingtemplate.FieldFileKey:             {Type: field.TypeString, Column: signingtemplate.FieldFileKey},
			signingtemplate.FieldFileName:            {Type: field.TypeString, Column: signingtemplate.FieldFileName},
			signingtemplate.FieldFileSize:            {Type: field.TypeInt64, Column: signingtemplate.FieldFileSize},
			signingtemplate.FieldFields:              {Type: field.TypeJSON, Column: signingtemplate.FieldFields},
			signingtemplate.FieldRevocationStampText: {Type: field.TypeString, Column: signingtemplate.FieldRevocationStampText},
		},
	}
	graph.MustAddE(
		"parent",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   category.ParentTable,
			Columns: []string{category.ParentColumn},
			Bidi:    false,
		},
		"Category",
		"Category",
	)
	graph.MustAddE(
		"children",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.ChildrenTable,
			Columns: []string{category.ChildrenColumn},
			Bidi:    false,
		},
		"Category",
		"Category",
	)
	graph.MustAddE(
		"documents",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.DocumentsTable,
			Columns: []string{category.DocumentsColumn},
			Bidi:    false,
		},
		"Category",
		"Document",
	)
	graph.MustAddE(
		"permissions",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.PermissionsTable,
			Columns: []string{category.PermissionsColumn},
			Bidi:    false,
		},
		"Category",
		"DocumentPermission",
	)
	graph.MustAddE(
		"category",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.CategoryTable,
			Columns: []string{document.CategoryColumn},
			Bidi:    false,
		},
		"Document",
		"Category",
	)
	graph.MustAddE(
		"permissions",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.PermissionsTable,
			Columns: []string{document.PermissionsColumn},
			Bidi:    false,
		},
		"Document",
		"DocumentPermission",
	)
	graph.MustAddE(
		"category",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentpermission.CategoryTable,
			Columns: []string{documentpermission.CategoryColumn},
			Bidi:    false,
		},
		"DocumentPermission",
		"Category",
	)
	graph.MustAddE(
		"document",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentpermission.DocumentTable,
			Columns: []string{documentpermission.DocumentColumn},
			Bidi:    false,
		},
		"DocumentPermission",
		"Document",
	)
	graph.MustAddE(
		"signing_request",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   signingrecipient.SigningRequestTable,
			Columns: []string{signingrecipient.SigningRequestColumn},
			Bidi:    false,
		},
		"SigningRecipient",
		"SigningRequest",
	)
	graph.MustAddE(
		"recipients",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   signingrequest.RecipientsTable,
			Columns: []string{signingrequest.RecipientsColumn},
			Bidi:    false,
		},
		"SigningRequest",
		"SigningRecipient",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *AuditLogQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the AuditLogQuery builder.
func (_q *AuditLogQuery) Filter() *AuditLogFilter {
	return &AuditLogFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *AuditLogMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the AuditLogMutation builder.
func (m *AuditLogMutation) Filter() *AuditLogFilter {
	return &AuditLogFilter{config: m.config, predicateAdder: m}
}

// AuditLogFilter provides a generic filtering capability at runtime for AuditLogQuery.
type AuditLogFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *AuditLogFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *AuditLogFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(auditlog.FieldID))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *AuditLogFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(auditlog.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *AuditLogFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(auditlog.FieldUpdateTime))
}

// WhereDeleteTime applies the entql time.Time predicate on the delete_time field.
func (f *AuditLogFilter) WhereDeleteTime(p entql.TimeP) {
	f.Where(p.Field(auditlog.FieldDeleteTime))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *AuditLogFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(auditlog.FieldTenantID))
}

// WhereAuditID applies the entql string predicate on the audit_id field.
func (f *AuditLogFilter) WhereAuditID(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldAuditID))
}

// WhereRequestID applies the entql string predicate on the request_id field.
func (f *AuditLogFilter) WhereRequestID(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldRequestID))
}

// WhereOperation applies the entql string predicate on the operation field.
func (f *AuditLogFilter) WhereOperation(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldOperation))
}

// WhereServiceName applies the entql string predicate on the service_name field.
func (f *AuditLogFilter) WhereServiceName(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldServiceName))
}

// WhereClientID applies the entql string predicate on the client_id field.
func (f *AuditLogFilter) WhereClientID(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldClientID))
}

// WhereClientCommonName applies the entql string predicate on the client_common_name field.
func (f *AuditLogFilter) WhereClientCommonName(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldClientCommonName))
}

// WhereClientOrganization applies the entql string predicate on the client_organization field.
func (f *AuditLogFilter) WhereClientOrganization(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldClientOrganization))
}

// WhereClientSerialNumber applies the entql string predicate on the client_serial_number field.
func (f *AuditLogFilter) WhereClientSerialNumber(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldClientSerialNumber))
}

// WhereIsAuthenticated applies the entql bool predicate on the is_authenticated field.
func (f *AuditLogFilter) WhereIsAuthenticated(p entql.BoolP) {
	f.Where(p.Field(auditlog.FieldIsAuthenticated))
}

// WhereSuccess applies the entql bool predicate on the success field.
func (f *AuditLogFilter) WhereSuccess(p entql.BoolP) {
	f.Where(p.Field(auditlog.FieldSuccess))
}

// WhereErrorCode applies the entql int32 predicate on the error_code field.
func (f *AuditLogFilter) WhereErrorCode(p entql.Int32P) {
	f.Where(p.Field(auditlog.FieldErrorCode))
}

// WhereErrorMessage applies the entql string predicate on the error_message field.
func (f *AuditLogFilter) WhereErrorMessage(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldErrorMessage))
}

// WhereLatencyMs applies the entql int64 predicate on the latency_ms field.
func (f *AuditLogFilter) WhereLatencyMs(p entql.Int64P) {
	f.Where(p.Field(auditlog.FieldLatencyMs))
}

// WherePeerAddress applies the entql string predicate on the peer_address field.
func (f *AuditLogFilter) WherePeerAddress(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldPeerAddress))
}

// WhereGeoLocation applies the entql json.RawMessage predicate on the geo_location field.
func (f *AuditLogFilter) WhereGeoLocation(p entql.BytesP) {
	f.Where(p.Field(auditlog.FieldGeoLocation))
}

// WhereLogHash applies the entql string predicate on the log_hash field.
func (f *AuditLogFilter) WhereLogHash(p entql.StringP) {
	f.Where(p.Field(auditlog.FieldLogHash))
}

// WhereSignature applies the entql []byte predicate on the signature field.
func (f *AuditLogFilter) WhereSignature(p entql.BytesP) {
	f.Where(p.Field(auditlog.FieldSignature))
}

// WhereMetadata applies the entql json.RawMessage predicate on the metadata field.
func (f *AuditLogFilter) WhereMetadata(p entql.BytesP) {
	f.Where(p.Field(auditlog.FieldMetadata))
}

// addPredicate implements the predicateAdder interface.
func (_q *CategoryQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the CategoryQuery builder.
func (_q *CategoryQuery) Filter() *CategoryFilter {
	return &CategoryFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *CategoryMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the CategoryMutation builder.
func (m *CategoryMutation) Filter() *CategoryFilter {
	return &CategoryFilter{config: m.config, predicateAdder: m}
}

// CategoryFilter provides a generic filtering capability at runtime for CategoryQuery.
type CategoryFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *CategoryFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql string predicate on the id field.
func (f *CategoryFilter) WhereID(p entql.StringP) {
	f.Where(p.Field(category.FieldID))
}

// WhereCreateBy applies the entql uint32 predicate on the create_by field.
func (f *CategoryFilter) WhereCreateBy(p entql.Uint32P) {
	f.Where(p.Field(category.FieldCreateBy))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *CategoryFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(category.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *CategoryFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(category.FieldUpdateTime))
}

// WhereDeleteTime applies the entql time.Time predicate on the delete_time field.
func (f *CategoryFilter) WhereDeleteTime(p entql.TimeP) {
	f.Where(p.Field(category.FieldDeleteTime))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *CategoryFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(category.FieldTenantID))
}

// WhereParentID applies the entql string predicate on the parent_id field.
func (f *CategoryFilter) WhereParentID(p entql.StringP) {
	f.Where(p.Field(category.FieldParentID))
}

// WhereName applies the entql string predicate on the name field.
func (f *CategoryFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(category.FieldName))
}

// WherePath applies the entql string predicate on the path field.
func (f *CategoryFilter) WherePath(p entql.StringP) {
	f.Where(p.Field(category.FieldPath))
}

// WhereDescription applies the entql string predicate on the description field.
func (f *CategoryFilter) WhereDescription(p entql.StringP) {
	f.Where(p.Field(category.FieldDescription))
}

// WhereDepth applies the entql int32 predicate on the depth field.
func (f *CategoryFilter) WhereDepth(p entql.Int32P) {
	f.Where(p.Field(category.FieldDepth))
}

// WhereSortOrder applies the entql int32 predicate on the sort_order field.
func (f *CategoryFilter) WhereSortOrder(p entql.Int32P) {
	f.Where(p.Field(category.FieldSortOrder))
}

// WhereHasParent applies a predicate to check if query has an edge parent.
func (f *CategoryFilter) WhereHasParent() {
	f.Where(entql.HasEdge("parent"))
}

// WhereHasParentWith applies a predicate to check if query has an edge parent with a given conditions (other predicates).
func (f *CategoryFilter) WhereHasParentWith(preds ...predicate.Category) {
	f.Where(entql.HasEdgeWith("parent", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasChildren applies a predicate to check if query has an edge children.
func (f *CategoryFilter) WhereHasChildren() {
	f.Where(entql.HasEdge("children"))
}

// WhereHasChildrenWith applies a predicate to check if query has an edge children with a given conditions (other predicates).
func (f *CategoryFilter) WhereHasChildrenWith(preds ...predicate.Category) {
	f.Where(entql.HasEdgeWith("children", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasDocuments applies a predicate to check if query has an edge documents.
func (f *CategoryFilter) WhereHasDocuments() {
	f.Where(entql.HasEdge("documents"))
}

// WhereHasDocumentsWith applies a predicate to check if query has an edge documents with a given conditions (other predicates).
func (f *CategoryFilter) WhereHasDocumentsWith(preds ...predicate.Document) {
	f.Where(entql.HasEdgeWith("documents", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasPermissions applies a predicate to check if query has an edge permissions.
func (f *CategoryFilter) WhereHasPermissions() {
	f.Where(entql.HasEdge("permissions"))
}

// WhereHasPermissionsWith applies a predicate to check if query has an edge permissions with a given conditions (other predicates).
func (f *CategoryFilter) WhereHasPermissionsWith(preds ...predicate.DocumentPermission) {
	f.Where(entql.HasEdgeWith("permissions", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *DocumentQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the DocumentQuery builder.
func (_q *DocumentQuery) Filter() *DocumentFilter {
	return &DocumentFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *DocumentMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the DocumentMutation builder.
func (m *DocumentMutation) Filter() *DocumentFilter {
	return &DocumentFilter{config: m.config, predicateAdder: m}
}

// DocumentFilter provides a generic filtering capability at runtime for DocumentQuery.
type DocumentFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *DocumentFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql string predicate on the id field.
func (f *DocumentFilter) WhereID(p entql.StringP) {
	f.Where(p.Field(document.FieldID))
}

// WhereCreateBy applies the entql uint32 predicate on the create_by field.
func (f *DocumentFilter) WhereCreateBy(p entql.Uint32P) {
	f.Where(p.Field(document.FieldCreateBy))
}

// WhereUpdateBy applies the entql uint32 predicate on the update_by field.
func (f *DocumentFilter) WhereUpdateBy(p entql.Uint32P) {
	f.Where(p.Field(document.FieldUpdateBy))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *DocumentFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(document.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *DocumentFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(document.FieldUpdateTime))
}

// WhereDeleteTime applies the entql time.Time predicate on the delete_time field.
func (f *DocumentFilter) WhereDeleteTime(p entql.TimeP) {
	f.Where(p.Field(document.FieldDeleteTime))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *DocumentFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(document.FieldTenantID))
}

// WhereCategoryID applies the entql string predicate on the category_id field.
func (f *DocumentFilter) WhereCategoryID(p entql.StringP) {
	f.Where(p.Field(document.FieldCategoryID))
}

// WhereName applies the entql string predicate on the name field.
func (f *DocumentFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(document.FieldName))
}

// WhereDescription applies the entql string predicate on the description field.
func (f *DocumentFilter) WhereDescription(p entql.StringP) {
	f.Where(p.Field(document.FieldDescription))
}

// WhereFileKey applies the entql string predicate on the file_key field.
func (f *DocumentFilter) WhereFileKey(p entql.StringP) {
	f.Where(p.Field(document.FieldFileKey))
}

// WhereFileName applies the entql string predicate on the file_name field.
func (f *DocumentFilter) WhereFileName(p entql.StringP) {
	f.Where(p.Field(document.FieldFileName))
}

// WhereFileSize applies the entql int64 predicate on the file_size field.
func (f *DocumentFilter) WhereFileSize(p entql.Int64P) {
	f.Where(p.Field(document.FieldFileSize))
}

// WhereMimeType applies the entql string predicate on the mime_type field.
func (f *DocumentFilter) WhereMimeType(p entql.StringP) {
	f.Where(p.Field(document.FieldMimeType))
}

// WhereChecksum applies the entql string predicate on the checksum field.
func (f *DocumentFilter) WhereChecksum(p entql.StringP) {
	f.Where(p.Field(document.FieldChecksum))
}

// WhereTags applies the entql json.RawMessage predicate on the tags field.
func (f *DocumentFilter) WhereTags(p entql.BytesP) {
	f.Where(p.Field(document.FieldTags))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *DocumentFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(document.FieldStatus))
}

// WhereSource applies the entql string predicate on the source field.
func (f *DocumentFilter) WhereSource(p entql.StringP) {
	f.Where(p.Field(document.FieldSource))
}

// WhereContentText applies the entql string predicate on the content_text field.
func (f *DocumentFilter) WhereContentText(p entql.StringP) {
	f.Where(p.Field(document.FieldContentText))
}

// WhereExtractedMetadata applies the entql json.RawMessage predicate on the extracted_metadata field.
func (f *DocumentFilter) WhereExtractedMetadata(p entql.BytesP) {
	f.Where(p.Field(document.FieldExtractedMetadata))
}

// WhereProcessingStatus applies the entql string predicate on the processing_status field.
func (f *DocumentFilter) WhereProcessingStatus(p entql.StringP) {
	f.Where(p.Field(document.FieldProcessingStatus))
}

// WhereHasCategory applies a predicate to check if query has an edge category.
func (f *DocumentFilter) WhereHasCategory() {
	f.Where(entql.HasEdge("category"))
}

// WhereHasCategoryWith applies a predicate to check if query has an edge category with a given conditions (other predicates).
func (f *DocumentFilter) WhereHasCategoryWith(preds ...predicate.Category) {
	f.Where(entql.HasEdgeWith("category", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasPermissions applies a predicate to check if query has an edge permissions.
func (f *DocumentFilter) WhereHasPermissions() {
	f.Where(entql.HasEdge("permissions"))
}

// WhereHasPermissionsWith applies a predicate to check if query has an edge permissions with a given conditions (other predicates).
func (f *DocumentFilter) WhereHasPermissionsWith(preds ...predicate.DocumentPermission) {
	f.Where(entql.HasEdgeWith("permissions", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *DocumentPermissionQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the DocumentPermissionQuery builder.
func (_q *DocumentPermissionQuery) Filter() *DocumentPermissionFilter {
	return &DocumentPermissionFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *DocumentPermissionMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the DocumentPermissionMutation builder.
func (m *DocumentPermissionMutation) Filter() *DocumentPermissionFilter {
	return &DocumentPermissionFilter{config: m.config, predicateAdder: m}
}

// DocumentPermissionFilter provides a generic filtering capability at runtime for DocumentPermissionQuery.
type DocumentPermissionFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *DocumentPermissionFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[3].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int predicate on the id field.
func (f *DocumentPermissionFilter) WhereID(p entql.IntP) {
	f.Where(p.Field(documentpermission.FieldID))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *DocumentPermissionFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(documentpermission.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *DocumentPermissionFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(documentpermission.FieldUpdateTime))
}

// WhereDeleteTime applies the entql time.Time predicate on the delete_time field.
func (f *DocumentPermissionFilter) WhereDeleteTime(p entql.TimeP) {
	f.Where(p.Field(documentpermission.FieldDeleteTime))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *DocumentPermissionFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(documentpermission.FieldTenantID))
}

// WhereResourceType applies the entql string predicate on the resource_type field.
func (f *DocumentPermissionFilter) WhereResourceType(p entql.StringP) {
	f.Where(p.Field(documentpermission.FieldResourceType))
}

// WhereResourceID applies the entql string predicate on the resource_id field.
func (f *DocumentPermissionFilter) WhereResourceID(p entql.StringP) {
	f.Where(p.Field(documentpermission.FieldResourceID))
}

// WhereRelation applies the entql string predicate on the relation field.
func (f *DocumentPermissionFilter) WhereRelation(p entql.StringP) {
	f.Where(p.Field(documentpermission.FieldRelation))
}

// WhereSubjectType applies the entql string predicate on the subject_type field.
func (f *DocumentPermissionFilter) WhereSubjectType(p entql.StringP) {
	f.Where(p.Field(documentpermission.FieldSubjectType))
}

// WhereSubjectID applies the entql string predicate on the subject_id field.
func (f *DocumentPermissionFilter) WhereSubjectID(p entql.StringP) {
	f.Where(p.Field(documentpermission.FieldSubjectID))
}

// WhereGrantedBy applies the entql uint32 predicate on the granted_by field.
func (f *DocumentPermissionFilter) WhereGrantedBy(p entql.Uint32P) {
	f.Where(p.Field(documentpermission.FieldGrantedBy))
}

// WhereExpiresAt applies the entql time.Time predicate on the expires_at field.
func (f *DocumentPermissionFilter) WhereExpiresAt(p entql.TimeP) {
	f.Where(p.Field(documentpermission.FieldExpiresAt))
}

// WhereHasCategory applies a predicate to check if query has an edge category.
func (f *DocumentPermissionFilter) WhereHasCategory() {
	f.Where(entql.HasEdge("category"))
}

// WhereHasCategoryWith applies a predicate to check if query has an edge category with a given conditions (other predicates).
func (f *DocumentPermissionFilter) WhereHasCategoryWith(preds ...predicate.Category) {
	f.Where(entql.HasEdgeWith("category", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasDocument applies a predicate to check if query has an edge document.
func (f *DocumentPermissionFilter) WhereHasDocument() {
	f.Where(entql.HasEdge("document"))
}

// WhereHasDocumentWith applies a predicate to check if query has an edge document with a given conditions (other predicates).
func (f *DocumentPermissionFilter) WhereHasDocumentWith(preds ...predicate.Document) {
	f.Where(entql.HasEdgeWith("document", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *SigningRecipientQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the SigningRecipientQuery builder.
func (_q *SigningRecipientQuery) Filter() *SigningRecipientFilter {
	return &SigningRecipientFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *SigningRecipientMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the SigningRecipientMutation builder.
func (m *SigningRecipientMutation) Filter() *SigningRecipientFilter {
	return &SigningRecipientFilter{config: m.config, predicateAdder: m}
}

// SigningRecipientFilter provides a generic filtering capability at runtime for SigningRecipientQuery.
type SigningRecipientFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *SigningRecipientFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[4].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql string predicate on the id field.
func (f *SigningRecipientFilter) WhereID(p entql.StringP) {
	f.Where(p.Field(signingrecipient.FieldID))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *SigningRecipientFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(signingrecipient.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *SigningRecipientFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(signingrecipient.FieldUpdateTime))
}

// WhereDeleteTime applies the entql time.Time predicate on the delete_time field.
func (f *SigningRecipientFilter) WhereDeleteTime(p entql.TimeP) {
	f.Where(p.Field(signingrecipient.FieldDeleteTime))
}

// WhereSigningRequestID applies the entql string predicate on the signing_request_id field.
func (f *SigningRecipientFilter) WhereSigningRequestID(p entql.StringP) {
	f.Where(p.Field(signingrecipient.FieldSigningRequestID))
}

// WhereEmail applies the entql string predicate on the email field.
func (f *SigningRecipientFilter) WhereEmail(p entql.StringP) {
	f.Where(p.Field(signingrecipient.FieldEmail))
}

// WhereName applies the entql string predicate on the name field.
func (f *SigningRecipientFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(signingrecipient.FieldName))
}

// WhereUserID applies the entql uint32 predicate on the user_id field.
func (f *SigningRecipientFilter) WhereUserID(p entql.Uint32P) {
	f.Where(p.Field(signingrecipient.FieldUserID))
}

// WhereSigningOrder applies the entql int32 predicate on the signing_order field.
func (f *SigningRecipientFilter) WhereSigningOrder(p entql.Int32P) {
	f.Where(p.Field(signingrecipient.FieldSigningOrder))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *SigningRecipientFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(signingrecipient.FieldStatus))
}

// WhereToken applies the entql string predicate on the token field.
func (f *SigningRecipientFilter) WhereToken(p entql.StringP) {
	f.Where(p.Field(signingrecipient.FieldToken))
}

// WhereSignedAt applies the entql time.Time predicate on the signed_at field.
func (f *SigningRecipientFilter) WhereSignedAt(p entql.TimeP) {
	f.Where(p.Field(signingrecipient.FieldSignedAt))
}

// WhereSignedIP applies the entql string predicate on the signed_ip field.
func (f *SigningRecipientFilter) WhereSignedIP(p entql.StringP) {
	f.Where(p.Field(signingrecipient.FieldSignedIP))
}

// WhereSignatureData applies the entql []byte predicate on the signature_data field.
func (f *SigningRecipientFilter) WhereSignatureData(p entql.BytesP) {
	f.Where(p.Field(signingrecipient.FieldSignatureData))
}

// WhereHasSigningRequest applies a predicate to check if query has an edge signing_request.
func (f *SigningRecipientFilter) WhereHasSigningRequest() {
	f.Where(entql.HasEdge("signing_request"))
}

// WhereHasSigningRequestWith applies a predicate to check if query has an edge signing_request with a given conditions (other predicates).
func (f *SigningRecipientFilter) WhereHasSigningRequestWith(preds ...predicate.SigningRequest) {
	f.Where(entql.HasEdgeWith("signing_request", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *SigningRequestQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the SigningRequestQuery builder.
func (_q *SigningRequestQuery) Filter() *SigningRequestFilter {
	return &SigningRequestFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *SigningRequestMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the SigningRequestMutation builder.
func (m *SigningRequestMutation) Filter() *SigningRequestFilter {
	return &SigningRequestFilter{config: m.config, predicateAdder: m}
}

// SigningRequestFilter provides a generic filtering capability at runtime for SigningRequestQuery.
type SigningRequestFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *SigningRequestFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[5].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql string predicate on the id field.
func (f *SigningRequestFilter) WhereID(p entql.StringP) {
	f.Where(p.Field(signingrequest.FieldID))
}

// WhereCreateBy applies the entql uint32 predicate on the create_by field.
func (f *SigningRequestFilter) WhereCreateBy(p entql.Uint32P) {
	f.Where(p.Field(signingrequest.FieldCreateBy))
}

// WhereUpdateBy applies the entql uint32 predicate on the update_by field.
func (f *SigningRequestFilter) WhereUpdateBy(p entql.Uint32P) {
	f.Where(p.Field(signingrequest.FieldUpdateBy))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *SigningRequestFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(signingrequest.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *SigningRequestFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(signingrequest.FieldUpdateTime))
}

// WhereDeleteTime applies the entql time.Time predicate on the delete_time field.
func (f *SigningRequestFilter) WhereDeleteTime(p entql.TimeP) {
	f.Where(p.Field(signingrequest.FieldDeleteTime))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *SigningRequestFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(signingrequest.FieldTenantID))
}

// WhereTemplateID applies the entql string predicate on the template_id field.
func (f *SigningRequestFilter) WhereTemplateID(p entql.StringP) {
	f.Where(p.Field(signingrequest.FieldTemplateID))
}

// WhereName applies the entql string predicate on the name field.
func (f *SigningRequestFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(signingrequest.FieldName))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *SigningRequestFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(signingrequest.FieldStatus))
}

// WhereSigningType applies the entql string predicate on the signing_type field.
func (f *SigningRequestFilter) WhereSigningType(p entql.StringP) {
	f.Where(p.Field(signingrequest.FieldSigningType))
}

// WhereOriginalFileKey applies the entql string predicate on the original_file_key field.
func (f *SigningRequestFilter) WhereOriginalFileKey(p entql.StringP) {
	f.Where(p.Field(signingrequest.FieldOriginalFileKey))
}

// WhereSignedFileKey applies the entql string predicate on the signed_file_key field.
func (f *SigningRequestFilter) WhereSignedFileKey(p entql.StringP) {
	f.Where(p.Field(signingrequest.FieldSignedFileKey))
}

// WhereFieldValues applies the entql json.RawMessage predicate on the field_values field.
func (f *SigningRequestFilter) WhereFieldValues(p entql.BytesP) {
	f.Where(p.Field(signingrequest.FieldFieldValues))
}

// WhereMessage applies the entql string predicate on the message field.
func (f *SigningRequestFilter) WhereMessage(p entql.StringP) {
	f.Where(p.Field(signingrequest.FieldMessage))
}

// WhereExpiresAt applies the entql time.Time predicate on the expires_at field.
func (f *SigningRequestFilter) WhereExpiresAt(p entql.TimeP) {
	f.Where(p.Field(signingrequest.FieldExpiresAt))
}

// WhereHasRecipients applies a predicate to check if query has an edge recipients.
func (f *SigningRequestFilter) WhereHasRecipients() {
	f.Where(entql.HasEdge("recipients"))
}

// WhereHasRecipientsWith applies a predicate to check if query has an edge recipients with a given conditions (other predicates).
func (f *SigningRequestFilter) WhereHasRecipientsWith(preds ...predicate.SigningRecipient) {
	f.Where(entql.HasEdgeWith("recipients", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *SigningTemplateQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the SigningTemplateQuery builder.
func (_q *SigningTemplateQuery) Filter() *SigningTemplateFilter {
	return &SigningTemplateFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *SigningTemplateMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the SigningTemplateMutation builder.
func (m *SigningTemplateMutation) Filter() *SigningTemplateFilter {
	return &SigningTemplateFilter{config: m.config, predicateAdder: m}
}

// SigningTemplateFilter provides a generic filtering capability at runtime for SigningTemplateQuery.
type SigningTemplateFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *SigningTemplateFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[6].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql string predicate on the id field.
func (f *SigningTemplateFilter) WhereID(p entql.StringP) {
	f.Where(p.Field(signingtemplate.FieldID))
}

// WhereCreateBy applies the entql uint32 predicate on the create_by field.
func (f *SigningTemplateFilter) WhereCreateBy(p entql.Uint32P) {
	f.Where(p.Field(signingtemplate.FieldCreateBy))
}

// WhereUpdateBy applies the entql uint32 predicate on the update_by field.
func (f *SigningTemplateFilter) WhereUpdateBy(p entql.Uint32P) {
	f.Where(p.Field(signingtemplate.FieldUpdateBy))
}

// WhereCreateTime applies the entql time.Time predicate on the create_time field.
func (f *SigningTemplateFilter) WhereCreateTime(p entql.TimeP) {
	f.Where(p.Field(signingtemplate.FieldCreateTime))
}

// WhereUpdateTime applies the entql time.Time predicate on the update_time field.
func (f *SigningTemplateFilter) WhereUpdateTime(p entql.TimeP) {
	f.Where(p.Field(signingtemplate.FieldUpdateTime))
}

// WhereDeleteTime applies the entql time.Time predicate on the delete_time field.
func (f *SigningTemplateFilter) WhereDeleteTime(p entql.TimeP) {
	f.Where(p.Field(signingtemplate.FieldDeleteTime))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *SigningTemplateFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(signingtemplate.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *SigningTemplateFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(signingtemplate.FieldName))
}

// WhereDescription applies the entql string predicate on the description field.
func (f *SigningTemplateFilter) WhereDescription(p entql.StringP) {
	f.Where(p.Field(signingtemplate.FieldDescription))
}

// WhereFileKey applies the entql string predicate on the file_key field.
func (f *SigningTemplateFilter) WhereFileKey(p entql.StringP) {
	f.Where(p.Field(signingtemplate.FieldFileKey))
}

// WhereFileName applies the entql string predicate on the file_name field.
func (f *SigningTemplateFilter) WhereFileName(p entql.StringP) {
	f.Where(p.Field(signingtemplate.FieldFileName))
}

// WhereFileSize applies the entql int64 predicate on the file_size field.
func (f *SigningTemplateFilter) WhereFileSize(p entql.Int64P) {
	f.Where(p.Field(signingtemplate.FieldFileSize))
}

// WhereFields applies the entql json.RawMessage predicate on the fields field.
func (f *SigningTemplateFilter) WhereFields(p entql.BytesP) {
	f.Where(p.Field(signingtemplate.FieldFields))
}

// WhereRevocationStampText applies the entql string predicate on the revocation_stamp_text field.
func (f *SigningTemplateFilter) WhereRevocationStampText(p entql.StringP) {
	f.Where(p.Field(signingtemplate.FieldRevocationStampText))
}
