// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingrecipient"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingrequest"
)

// SigningRecipientCreate is the builder for creating a SigningRecipient entity.
type SigningRecipientCreate struct {
	config
	mutation *SigningRecipientMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *SigningRecipientCreate) SetCreateTime(v time.Time) *SigningRecipientCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SigningRecipientCreate) SetNillableCreateTime(v *time.Time) *SigningRecipientCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SigningRecipientCreate) SetUpdateTime(v time.Time) *SigningRecipientCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SigningRecipientCreate) SetNillableUpdateTime(v *time.Time) *SigningRecipientCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *SigningRecipientCreate) SetDeleteTime(v time.Time) *SigningRecipientCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *SigningRecipientCreate) SetNillableDeleteTime(v *time.Time) *SigningRecipientCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetSigningRequestID sets the "signing_request_id" field.
func (_c *SigningRecipientCreate) SetSigningRequestID(v string) *SigningRecipientCreate {
	_c.mutation.SetSigningRequestID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *SigningRecipientCreate) SetEmail(v string) *SigningRecipientCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SigningRecipientCreate) SetName(v string) *SigningRecipientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SigningRecipientCreate) SetUserID(v uint32) *SigningRecipientCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *SigningRecipientCreate) SetNillableUserID(v *uint32) *SigningRecipientCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetSigningOrder sets the "signing_order" field.
func (_c *SigningRecipientCreate) SetSigningOrder(v int32) *SigningRecipientCreate {
	_c.mutation.SetSigningOrder(v)
	return _c
}

// SetNillableSigningOrder sets the "signing_order" field if the given value is not nil.
func (_c *SigningRecipientCreate) SetNillableSigningOrder(v *int32) *SigningRecipientCreate {
	if v != nil {
		_c.SetSigningOrder(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SigningRecipientCreate) SetStatus(v signingrecipient.Status) *SigningRecipientCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SigningRecipientCreate) SetNillableStatus(v *signingrecipient.Status) *SigningRecipientCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetToken sets the "token" field.
func (_c *SigningRecipientCreate) SetToken(v string) *SigningRecipientCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetSignedAt sets the "signed_at" field.
func (_c *SigningRecipientCreate) SetSignedAt(v time.Time) *SigningRecipientCreate {
	_c.mutation.SetSignedAt(v)
	return _c
}

// SetNillableSignedAt sets the "signed_at" field if the given value is not nil.
func (_c *SigningRecipientCreate) SetNillableSignedAt(v *time.Time) *SigningRecipientCreate {
	if v != nil {
		_c.SetSignedAt(*v)
	}
	return _c
}

// SetSignedIP sets the "signed_ip" field.
func (_c *SigningRecipientCreate) SetSignedIP(v string) *SigningRecipientCreate {
	_c.mutation.SetSignedIP(v)
	return _c
}

// SetNillableSignedIP sets the "signed_ip" field if the given value is not nil.
func (_c *SigningRecipientCreate) SetNillableSignedIP(v *string) *SigningRecipientCreate {
	if v != nil {
		_c.SetSignedIP(*v)
	}
	return _c
}

// SetSignatureData sets the "signature_data" field.
func (_c *SigningRecipientCreate) SetSignatureData(v []byte) *SigningRecipientCreate {
	_c.mutation.SetSignatureData(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SigningRecipientCreate) SetID(v string) *SigningRecipientCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSigningRequest sets the "signing_request" edge to the SigningRequest entity.
func (_c *SigningRecipientCreate) SetSigningRequest(v *SigningRequest) *SigningRecipientCreate {
	return _c.SetSigningRequestID(v.ID)
}

// Mutation returns the SigningRecipientMutation object of the builder.
func (_c *SigningRecipientCreate) Mutation() *SigningRecipientMutation {
	return _c.mutation
}

// Save creates the SigningRecipient in the database.
func (_c *SigningRecipientCreate) Save(ctx context.Context) (*SigningRecipient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SigningRecipientCreate) SaveX(ctx context.Context) *SigningRecipient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SigningRecipientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SigningRecipientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SigningRecipientCreate) defaults() {
	if _, ok := _c.mutation.SigningOrder(); !ok {
		v := signingrecipient.DefaultSigningOrder
		_c.mutation.SetSigningOrder(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := signingrecipient.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SigningRecipientCreate) check() error {
	if _, ok := _c.mutation.SigningRequestID(); !ok {
		return &ValidationError{Name: "signing_request_id", err: errors.New(`ent: missing required field "SigningRecipient.signing_request_id"`)}
	}
	if v, ok := _c.mutation.SigningRequestID(); ok {
		if err := signingrecipient.SigningRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "signing_request_id", err: fmt.Errorf(`ent: validator failed for field "SigningRecipient.signing_request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "SigningRecipient.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := signingrecipient.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SigningRecipient.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SigningRecipient.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := signingrecipient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SigningRecipient.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SigningOrder(); !ok {
		return &ValidationError{Name: "signing_order", err: errors.New(`ent: missing required field "SigningRecipient.signing_order"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SigningRecipient.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := signingrecipient.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SigningRecipient.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "SigningRecipient.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := signingrecipient.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "SigningRecipient.token": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SignedIP(); ok {
		if err := signingrecipient.SignedIPValidator(v); err != nil {
			return &ValidationError{Name: "signed_ip", err: fmt.Errorf(`ent: validator failed for field "SigningRecipient.signed_ip": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := signingrecipient.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SigningRecipient.id": %w`, err)}
		}
	}
	if len(_c.mutation.SigningRequestIDs()) == 0 {
		return &ValidationError{Name: "signing_request", err: errors.New(`ent: missing required edge "SigningRecipient.signing_request"`)}
	}
	return nil
}

func (_c *SigningRecipientCreate) sqlSave(ctx context.Context) (*SigningRecipient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SigningRecipient.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SigningRecipientCreate) createSpec() (*SigningRecipient, *sqlgraph.CreateSpec) {
	var (
		_node = &SigningRecipient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(signingrecipient.Table, sqlgraph.NewFieldSpec(signingrecipient.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(signingrecipient.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(signingrecipient.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(signingrecipient.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(signingrecipient.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(signingrecipient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(signingrecipient.FieldUserID, field.TypeUint32, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.SigningOrder(); ok {
		_spec.SetField(signingrecipient.FieldSigningOrder, field.TypeInt32, value)
		_node.SigningOrder = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(signingrecipient.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(signingrecipient.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.SignedAt(); ok {
		_spec.SetField(signingrecipient.FieldSignedAt, field.TypeTime, value)
		_node.SignedAt = &value
	}
	if value, ok := _c.mutation.SignedIP(); ok {
		_spec.SetField(signingrecipient.FieldSignedIP, field.TypeString, value)
		_node.SignedIP = value
	}
	if value, ok := _c.mutation.SignatureData(); ok {
		_spec.SetField(signingrecipient.FieldSignatureData, field.TypeBytes, value)
		_node.SignatureData = value
	}
	if nodes := _c.mutation.SigningRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   signingrecipient.SigningRequestTable,
			Columns: []string{signingrecipient.SigningRequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(signingrequest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SigningRequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SigningRecipient.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SigningRecipientUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *SigningRecipientCreate) OnConflict(opts ...sql.ConflictOption) *SigningRecipientUpsertOne {
	_c.conflict = opts
	return &SigningRecipientUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SigningRecipient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SigningRecipientCreate) OnConflictColumns(columns ...string) *SigningRecipientUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SigningRecipientUpsertOne{
		create: _c,
	}
}

type (
	// SigningRecipientUpsertOne is the builder for "upsert"-ing
	//  one SigningRecipient node.
	SigningRecipientUpsertOne struct {
		create *SigningRecipientCreate
	}

	// SigningRecipientUpsert is the "OnConflict" setter.
	SigningRecipientUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *SigningRecipientUpsert) SetUpdateTime(v time.Time) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateUpdateTime() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SigningRecipientUpsert) ClearUpdateTime() *SigningRecipientUpsert {
	u.SetNull(signingrecipient.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *SigningRecipientUpsert) SetDeleteTime(v time.Time) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateDeleteTime() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SigningRecipientUpsert) ClearDeleteTime() *SigningRecipientUpsert {
	u.SetNull(signingrecipient.FieldDeleteTime)
	return u
}

// SetSigningRequestID sets the "signing_request_id" field.
func (u *SigningRecipientUpsert) SetSigningRequestID(v string) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldSigningRequestID, v)
	return u
}

// UpdateSigningRequestID sets the "signing_request_id" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateSigningRequestID() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldSigningRequestID)
	return u
}

// SetEmail sets the "email" field.
func (u *SigningRecipientUpsert) SetEmail(v string) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateEmail() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldEmail)
	return u
}

// SetName sets the "name" field.
func (u *SigningRecipientUpsert) SetName(v string) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateName() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldName)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SigningRecipientUpsert) SetUserID(v uint32) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateUserID() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *SigningRecipientUpsert) AddUserID(v uint32) *SigningRecipientUpsert {
	u.Add(signingrecipient.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *SigningRecipientUpsert) ClearUserID() *SigningRecipientUpsert {
	u.SetNull(signingrecipient.FieldUserID)
	return u
}

// SetSigningOrder sets the "signing_order" field.
func (u *SigningRecipientUpsert) SetSigningOrder(v int32) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldSigningOrder, v)
	return u
}

// UpdateSigningOrder sets the "signing_order" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateSigningOrder() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldSigningOrder)
	return u
}

// AddSigningOrder adds v to the "signing_order" field.
func (u *SigningRecipientUpsert) AddSigningOrder(v int32) *SigningRecipientUpsert {
	u.Add(signingrecipient.FieldSigningOrder, v)
	return u
}

// SetStatus sets the "status" field.
func (u *SigningRecipientUpsert) SetStatus(v signingrecipient.Status) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateStatus() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldStatus)
	return u
}

// SetToken sets the "token" field.
func (u *SigningRecipientUpsert) SetToken(v string) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldToken, v)
	return u
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateToken() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldToken)
	return u
}

// SetSignedAt sets the "signed_at" field.
func (u *SigningRecipientUpsert) SetSignedAt(v time.Time) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldSignedAt, v)
	return u
}

// UpdateSignedAt sets the "signed_at" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateSignedAt() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldSignedAt)
	return u
}

// ClearSignedAt clears the value of the "signed_at" field.
func (u *SigningRecipientUpsert) ClearSignedAt() *SigningRecipientUpsert {
	u.SetNull(signingrecipient.FieldSignedAt)
	return u
}

// SetSignedIP sets the "signed_ip" field.
func (u *SigningRecipientUpsert) SetSignedIP(v string) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldSignedIP, v)
	return u
}

// UpdateSignedIP sets the "signed_ip" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateSignedIP() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldSignedIP)
	return u
}

// ClearSignedIP clears the value of the "signed_ip" field.
func (u *SigningRecipientUpsert) ClearSignedIP() *SigningRecipientUpsert {
	u.SetNull(signingrecipient.FieldSignedIP)
	return u
}

// SetSignatureData sets the "signature_data" field.
func (u *SigningRecipientUpsert) SetSignatureData(v []byte) *SigningRecipientUpsert {
	u.Set(signingrecipient.FieldSignatureData, v)
	return u
}

// UpdateSignatureData sets the "signature_data" field to the value that was provided on create.
func (u *SigningRecipientUpsert) UpdateSignatureData() *SigningRecipientUpsert {
	u.SetExcluded(signingrecipient.FieldSignatureData)
	return u
}

// ClearSignatureData clears the value of the "signature_data" field.
func (u *SigningRecipientUpsert) ClearSignatureData() *SigningRecipientUpsert {
	u.SetNull(signingrecipient.FieldSignatureData)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SigningRecipient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(signingrecipient.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SigningRecipientUpsertOne) UpdateNewValues() *SigningRecipientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(signingrecipient.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(signingrecipient.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SigningRecipient.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SigningRecipientUpsertOne) Ignore() *SigningRecipientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SigningRecipientUpsertOne) DoNothing() *SigningRecipientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SigningRecipientCreate.OnConflict
// documentation for more info.
func (u *SigningRecipientUpsertOne) Update(set func(*SigningRecipientUpsert)) *SigningRecipientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SigningRecipientUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SigningRecipientUpsertOne) SetUpdateTime(v time.Time) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateUpdateTime() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SigningRecipientUpsertOne) ClearUpdateTime() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SigningRecipientUpsertOne) SetDeleteTime(v time.Time) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateDeleteTime() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SigningRecipientUpsertOne) ClearDeleteTime() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearDeleteTime()
	})
}

// SetSigningRequestID sets the "signing_request_id" field.
func (u *SigningRecipientUpsertOne) SetSigningRequestID(v string) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetSigningRequestID(v)
	})
}

// UpdateSigningRequestID sets the "signing_request_id" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateSigningRequestID() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateSigningRequestID()
	})
}

// SetEmail sets the "email" field.
func (u *SigningRecipientUpsertOne) SetEmail(v string) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateEmail() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateEmail()
	})
}

// SetName sets the "name" field.
func (u *SigningRecipientUpsertOne) SetName(v string) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateName() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateName()
	})
}

// SetUserID sets the "user_id" field.
func (u *SigningRecipientUpsertOne) SetUserID(v uint32) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SigningRecipientUpsertOne) AddUserID(v uint32) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateUserID() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *SigningRecipientUpsertOne) ClearUserID() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearUserID()
	})
}

// SetSigningOrder sets the "signing_order" field.
func (u *SigningRecipientUpsertOne) SetSigningOrder(v int32) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetSigningOrder(v)
	})
}

// AddSigningOrder adds v to the "signing_order" field.
func (u *SigningRecipientUpsertOne) AddSigningOrder(v int32) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.AddSigningOrder(v)
	})
}

// UpdateSigningOrder sets the "signing_order" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateSigningOrder() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateSigningOrder()
	})
}

// SetStatus sets the "status" field.
func (u *SigningRecipientUpsertOne) SetStatus(v signingrecipient.Status) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateStatus() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateStatus()
	})
}

// SetToken sets the "token" field.
func (u *SigningRecipientUpsertOne) SetToken(v string) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateToken() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateToken()
	})
}

// SetSignedAt sets the "signed_at" field.
func (u *SigningRecipientUpsertOne) SetSignedAt(v time.Time) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetSignedAt(v)
	})
}

// UpdateSignedAt sets the "signed_at" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateSignedAt() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateSignedAt()
	})
}

// ClearSignedAt clears the value of the "signed_at" field.
func (u *SigningRecipientUpsertOne) ClearSignedAt() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearSignedAt()
	})
}

// SetSignedIP sets the "signed_ip" field.
func (u *SigningRecipientUpsertOne) SetSignedIP(v string) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetSignedIP(v)
	})
}

// UpdateSignedIP sets the "signed_ip" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateSignedIP() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateSignedIP()
	})
}

// ClearSignedIP clears the value of the "signed_ip" field.
func (u *SigningRecipientUpsertOne) ClearSignedIP() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearSignedIP()
	})
}

// SetSignatureData sets the "signature_data" field.
func (u *SigningRecipientUpsertOne) SetSignatureData(v []byte) *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetSignatureData(v)
	})
}

// UpdateSignatureData sets the "signature_data" field to the value that was provided on create.
func (u *SigningRecipientUpsertOne) UpdateSignatureData() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateSignatureData()
	})
}

// ClearSignatureData clears the value of the "signature_data" field.
func (u *SigningRecipientUpsertOne) ClearSignatureData() *SigningRecipientUpsertOne {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearSignatureData()
	})
}

// Exec executes the query.
func (u *SigningRecipientUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SigningRecipientCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SigningRecipientUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SigningRecipientUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SigningRecipientUpsertOne.ID is not supported by MySQL driver. Use SigningRecipientUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SigningRecipientUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SigningRecipientCreateBulk is the builder for creating many SigningRecipient entities in bulk.
type SigningRecipientCreateBulk struct {
	config
	err      error
	builders []*SigningRecipientCreate
	conflict []sql.ConflictOption
}

// Save creates the SigningRecipient entities in the database.
func (_c *SigningRecipientCreateBulk) Save(ctx context.Context) ([]*SigningRecipient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SigningRecipient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SigningRecipientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SigningRecipientCreateBulk) SaveX(ctx context.Context) []*SigningRecipient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SigningRecipientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SigningRecipientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SigningRecipient.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SigningRecipientUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *SigningRecipientCreateBulk) OnConflict(opts ...sql.ConflictOption) *SigningRecipientUpsertBulk {
	_c.conflict = opts
	return &SigningRecipientUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SigningRecipient.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SigningRecipientCreateBulk) OnConflictColumns(columns ...string) *SigningRecipientUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SigningRecipientUpsertBulk{
		create: _c,
	}
}

// SigningRecipientUpsertBulk is the builder for "upsert"-ing
// a bulk of SigningRecipient nodes.
type SigningRecipientUpsertBulk struct {
	create *SigningRecipientCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SigningRecipient.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(signingrecipient.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SigningRecipientUpsertBulk) UpdateNewValues() *SigningRecipientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(signingrecipient.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(signingrecipient.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SigningRecipient.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SigningRecipientUpsertBulk) Ignore() *SigningRecipientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SigningRecipientUpsertBulk) DoNothing() *SigningRecipientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SigningRecipientCreateBulk.OnConflict
// documentation for more info.
func (u *SigningRecipientUpsertBulk) Update(set func(*SigningRecipientUpsert)) *SigningRecipientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SigningRecipientUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SigningRecipientUpsertBulk) SetUpdateTime(v time.Time) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateUpdateTime() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SigningRecipientUpsertBulk) ClearUpdateTime() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SigningRecipientUpsertBulk) SetDeleteTime(v time.Time) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateDeleteTime() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SigningRecipientUpsertBulk) ClearDeleteTime() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearDeleteTime()
	})
}

// SetSigningRequestID sets the "signing_request_id" field.
func (u *SigningRecipientUpsertBulk) SetSigningRequestID(v string) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetSigningRequestID(v)
	})
}

// UpdateSigningRequestID sets the "signing_request_id" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateSigningRequestID() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateSigningRequestID()
	})
}

// SetEmail sets the "email" field.
func (u *SigningRecipientUpsertBulk) SetEmail(v string) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateEmail() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateEmail()
	})
}

// SetName sets the "name" field.
func (u *SigningRecipientUpsertBulk) SetName(v string) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateName() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateName()
	})
}

// SetUserID sets the "user_id" field.
func (u *SigningRecipientUpsertBulk) SetUserID(v uint32) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SigningRecipientUpsertBulk) AddUserID(v uint32) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateUserID() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *SigningRecipientUpsertBulk) ClearUserID() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearUserID()
	})
}

// SetSigningOrder sets the "signing_order" field.
func (u *SigningRecipientUpsertBulk) SetSigningOrder(v int32) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetSigningOrder(v)
	})
}

// AddSigningOrder adds v to the "signing_order" field.
func (u *SigningRecipientUpsertBulk) AddSigningOrder(v int32) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.AddSigningOrder(v)
	})
}

// UpdateSigningOrder sets the "signing_order" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateSigningOrder() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateSigningOrder()
	})
}

// SetStatus sets the "status" field.
func (u *SigningRecipientUpsertBulk) SetStatus(v signingrecipient.Status) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateStatus() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateStatus()
	})
}

// SetToken sets the "token" field.
func (u *SigningRecipientUpsertBulk) SetToken(v string) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateToken() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateToken()
	})
}

// SetSignedAt sets the "signed_at" field.
func (u *SigningRecipientUpsertBulk) SetSignedAt(v time.Time) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetSignedAt(v)
	})
}

// UpdateSignedAt sets the "signed_at" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateSignedAt() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateSignedAt()
	})
}

// ClearSignedAt clears the value of the "signed_at" field.
func (u *SigningRecipientUpsertBulk) ClearSignedAt() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearSignedAt()
	})
}

// SetSignedIP sets the "signed_ip" field.
func (u *SigningRecipientUpsertBulk) SetSignedIP(v string) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetSignedIP(v)
	})
}

// UpdateSignedIP sets the "signed_ip" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateSignedIP() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateSignedIP()
	})
}

// ClearSignedIP clears the value of the "signed_ip" field.
func (u *SigningRecipientUpsertBulk) ClearSignedIP() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearSignedIP()
	})
}

// SetSignatureData sets the "signature_data" field.
func (u *SigningRecipientUpsertBulk) SetSignatureData(v []byte) *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.SetSignatureData(v)
	})
}

// UpdateSignatureData sets the "signature_data" field to the value that was provided on create.
func (u *SigningRecipientUpsertBulk) UpdateSignatureData() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.UpdateSignatureData()
	})
}

// ClearSignatureData clears the value of the "signature_data" field.
func (u *SigningRecipientUpsertBulk) ClearSignatureData() *SigningRecipientUpsertBulk {
	return u.Update(func(s *SigningRecipientUpsert) {
		s.ClearSignatureData()
	})
}

// Exec executes the query.
func (u *SigningRecipientUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SigningRecipientCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SigningRecipientCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SigningRecipientUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
