// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingrecipient"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingrequest"
)

// SigningRecipient is the model entity for the SigningRecipient schema.
type SigningRecipient struct {
	config `json:"-"`
	// ID of the ent.
	// UUID primary key
	ID string `json:"id,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// Reference to signing request
	SigningRequestID string `json:"signing_request_id,omitempty"`
	// Recipient email address
	Email string `json:"email,omitempty"`
	// Recipient display name
	Name string `json:"name,omitempty"`
	// Order in which recipients sign (1-based)
	SigningOrder int32 `json:"signing_order,omitempty"`
	// Recipient signing status
	Status signingrecipient.Status `json:"status,omitempty"`
	// Unique signing token (64-char hex)
	Token string `json:"token,omitempty"`
	// Timestamp when recipient signed
	SignedAt *time.Time `json:"signed_at,omitempty"`
	// IP address of signer
	SignedIP string `json:"signed_ip,omitempty"`
	// Signature image data (PNG)
	SignatureData []byte `json:"signature_data,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SigningRecipientQuery when eager-loading is set.
	Edges        SigningRecipientEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SigningRecipientEdges holds the relations/edges for other nodes in the graph.
type SigningRecipientEdges struct {
	// Parent signing request
	SigningRequest *SigningRequest `json:"signing_request,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SigningRequestOrErr returns the SigningRequest value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SigningRecipientEdges) SigningRequestOrErr() (*SigningRequest, error) {
	if e.SigningRequest != nil {
		return e.SigningRequest, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: signingrequest.Label}
	}
	return nil, &NotLoadedError{edge: "signing_request"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SigningRecipient) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case signingrecipient.FieldSignatureData:
			values[i] = new([]byte)
		case signingrecipient.FieldSigningOrder:
			values[i] = new(sql.NullInt64)
		case signingrecipient.FieldID, signingrecipient.FieldSigningRequestID, signingrecipient.FieldEmail, signingrecipient.FieldName, signingrecipient.FieldStatus, signingrecipient.FieldToken, signingrecipient.FieldSignedIP:
			values[i] = new(sql.NullString)
		case signingrecipient.FieldCreateTime, signingrecipient.FieldUpdateTime, signingrecipient.FieldDeleteTime, signingrecipient.FieldSignedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SigningRecipient fields.
func (_m *SigningRecipient) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case signingrecipient.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case signingrecipient.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case signingrecipient.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case signingrecipient.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case signingrecipient.FieldSigningRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signing_request_id", values[i])
			} else if value.Valid {
				_m.SigningRequestID = value.String
			}
		case signingrecipient.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case signingrecipient.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case signingrecipient.FieldSigningOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field signing_order", values[i])
			} else if value.Valid {
				_m.SigningOrder = int32(value.Int64)
			}
		case signingrecipient.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = signingrecipient.Status(value.String)
			}
		case signingrecipient.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case signingrecipient.FieldSignedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field signed_at", values[i])
			} else if value.Valid {
				_m.SignedAt = new(time.Time)
				*_m.SignedAt = value.Time
			}
		case signingrecipient.FieldSignedIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signed_ip", values[i])
			} else if value.Valid {
				_m.SignedIP = value.String
			}
		case signingrecipient.FieldSignatureData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field signature_data", values[i])
			} else if value != nil {
				_m.SignatureData = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SigningRecipient.
// This includes values selected through modifiers, order, etc.
func (_m *SigningRecipient) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySigningRequest queries the "signing_request" edge of the SigningRecipient entity.
func (_m *SigningRecipient) QuerySigningRequest() *SigningRequestQuery {
	return NewSigningRecipientClient(_m.config).QuerySigningRequest(_m)
}

// Update returns a builder for updating this SigningRecipient.
// Note that you need to call SigningRecipient.Unwrap() before calling this method if this SigningRecipient
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SigningRecipient) Update() *SigningRecipientUpdateOne {
	return NewSigningRecipientClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SigningRecipient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SigningRecipient) Unwrap() *SigningRecipient {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SigningRecipient is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SigningRecipient) String() string {
	var builder strings.Builder
	builder.WriteString("SigningRecipient(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("signing_request_id=")
	builder.WriteString(_m.SigningRequestID)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("signing_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SigningOrder))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	if v := _m.SignedAt; v != nil {
		builder.WriteString("signed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("signed_ip=")
	builder.WriteString(_m.SignedIP)
	builder.WriteString(", ")
	builder.WriteString("signature_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.SignatureData))
	builder.WriteByte(')')
	return builder.String()
}

// SigningRecipients is a parsable slice of SigningRecipient.
type SigningRecipients []*SigningRecipient
