// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingrecipient"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingrequest"
)

// SigningRequestCreate is the builder for creating a SigningRequest entity.
type SigningRequestCreate struct {
	config
	mutation *SigningRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *SigningRequestCreate) SetCreateBy(v uint32) *SigningRequestCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableCreateBy(v *uint32) *SigningRequestCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *SigningRequestCreate) SetUpdateBy(v uint32) *SigningRequestCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableUpdateBy(v *uint32) *SigningRequestCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *SigningRequestCreate) SetCreateTime(v time.Time) *SigningRequestCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableCreateTime(v *time.Time) *SigningRequestCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SigningRequestCreate) SetUpdateTime(v time.Time) *SigningRequestCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableUpdateTime(v *time.Time) *SigningRequestCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *SigningRequestCreate) SetDeleteTime(v time.Time) *SigningRequestCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableDeleteTime(v *time.Time) *SigningRequestCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *SigningRequestCreate) SetTenantID(v uint32) *SigningRequestCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableTenantID(v *uint32) *SigningRequestCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *SigningRequestCreate) SetTemplateID(v string) *SigningRequestCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SigningRequestCreate) SetName(v string) *SigningRequestCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SigningRequestCreate) SetStatus(v signingrequest.Status) *SigningRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableStatus(v *signingrequest.Status) *SigningRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSigningType sets the "signing_type" field.
func (_c *SigningRequestCreate) SetSigningType(v signingrequest.SigningType) *SigningRequestCreate {
	_c.mutation.SetSigningType(v)
	return _c
}

// SetNillableSigningType sets the "signing_type" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableSigningType(v *signingrequest.SigningType) *SigningRequestCreate {
	if v != nil {
		_c.SetSigningType(*v)
	}
	return _c
}

// SetOriginalFileKey sets the "original_file_key" field.
func (_c *SigningRequestCreate) SetOriginalFileKey(v string) *SigningRequestCreate {
	_c.mutation.SetOriginalFileKey(v)
	return _c
}

// SetNillableOriginalFileKey sets the "original_file_key" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableOriginalFileKey(v *string) *SigningRequestCreate {
	if v != nil {
		_c.SetOriginalFileKey(*v)
	}
	return _c
}

// SetSignedFileKey sets the "signed_file_key" field.
func (_c *SigningRequestCreate) SetSignedFileKey(v string) *SigningRequestCreate {
	_c.mutation.SetSignedFileKey(v)
	return _c
}

// SetNillableSignedFileKey sets the "signed_file_key" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableSignedFileKey(v *string) *SigningRequestCreate {
	if v != nil {
		_c.SetSignedFileKey(*v)
	}
	return _c
}

// SetFieldValues sets the "field_values" field.
func (_c *SigningRequestCreate) SetFieldValues(v []schema.SigningFieldValueDef) *SigningRequestCreate {
	_c.mutation.SetFieldValues(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *SigningRequestCreate) SetMessage(v string) *SigningRequestCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableMessage(v *string) *SigningRequestCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SigningRequestCreate) SetExpiresAt(v time.Time) *SigningRequestCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *SigningRequestCreate) SetNillableExpiresAt(v *time.Time) *SigningRequestCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SigningRequestCreate) SetID(v string) *SigningRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddRecipientIDs adds the "recipients" edge to the SigningRecipient entity by IDs.
func (_c *SigningRequestCreate) AddRecipientIDs(ids ...string) *SigningRequestCreate {
	_c.mutation.AddRecipientIDs(ids...)
	return _c
}

// AddRecipients adds the "recipients" edges to the SigningRecipient entity.
func (_c *SigningRequestCreate) AddRecipients(v ...*SigningRecipient) *SigningRequestCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecipientIDs(ids...)
}

// Mutation returns the SigningRequestMutation object of the builder.
func (_c *SigningRequestCreate) Mutation() *SigningRequestMutation {
	return _c.mutation
}

// Save creates the SigningRequest in the database.
func (_c *SigningRequestCreate) Save(ctx context.Context) (*SigningRequest, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SigningRequestCreate) SaveX(ctx context.Context) *SigningRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SigningRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SigningRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SigningRequestCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := signingrequest.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := signingrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SigningType(); !ok {
		v := signingrequest.DefaultSigningType
		_c.mutation.SetSigningType(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SigningRequestCreate) check() error {
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "SigningRequest.template_id"`)}
	}
	if v, ok := _c.mutation.TemplateID(); ok {
		if err := signingrequest.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "SigningRequest.template_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SigningRequest.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := signingrequest.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SigningRequest.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SigningRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := signingrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SigningRequest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SigningType(); !ok {
		return &ValidationError{Name: "signing_type", err: errors.New(`ent: missing required field "SigningRequest.signing_type"`)}
	}
	if v, ok := _c.mutation.SigningType(); ok {
		if err := signingrequest.SigningTypeValidator(v); err != nil {
			return &ValidationError{Name: "signing_type", err: fmt.Errorf(`ent: validator failed for field "SigningRequest.signing_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OriginalFileKey(); ok {
		if err := signingrequest.OriginalFileKeyValidator(v); err != nil {
			return &ValidationError{Name: "original_file_key", err: fmt.Errorf(`ent: validator failed for field "SigningRequest.original_file_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SignedFileKey(); ok {
		if err := signingrequest.SignedFileKeyValidator(v); err != nil {
			return &ValidationError{Name: "signed_file_key", err: fmt.Errorf(`ent: validator failed for field "SigningRequest.signed_file_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Message(); ok {
		if err := signingrequest.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "SigningRequest.message": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := signingrequest.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SigningRequest.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SigningRequestCreate) sqlSave(ctx context.Context) (*SigningRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SigningRequest.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SigningRequestCreate) createSpec() (*SigningRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &SigningRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(signingrequest.Table, sqlgraph.NewFieldSpec(signingrequest.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(signingrequest.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(signingrequest.FieldUpdateBy, field.TypeUint32, value)
		_node.UpdateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(signingrequest.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(signingrequest.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(signingrequest.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(signingrequest.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(signingrequest.FieldTemplateID, field.TypeString, value)
		_node.TemplateID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(signingrequest.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(signingrequest.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SigningType(); ok {
		_spec.SetField(signingrequest.FieldSigningType, field.TypeEnum, value)
		_node.SigningType = value
	}
	if value, ok := _c.mutation.OriginalFileKey(); ok {
		_spec.SetField(signingrequest.FieldOriginalFileKey, field.TypeString, value)
		_node.OriginalFileKey = value
	}
	if value, ok := _c.mutation.SignedFileKey(); ok {
		_spec.SetField(signingrequest.FieldSignedFileKey, field.TypeString, value)
		_node.SignedFileKey = value
	}
	if value, ok := _c.mutation.FieldValues(); ok {
		_spec.SetField(signingrequest.FieldFieldValues, field.TypeJSON, value)
		_node.FieldValues = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(signingrequest.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(signingrequest.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if nodes := _c.mutation.RecipientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   signingrequest.RecipientsTable,
			Columns: []string{signingrequest.RecipientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(signingrecipient.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SigningRequest.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SigningRequestUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SigningRequestCreate) OnConflict(opts ...sql.ConflictOption) *SigningRequestUpsertOne {
	_c.conflict = opts
	return &SigningRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SigningRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SigningRequestCreate) OnConflictColumns(columns ...string) *SigningRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SigningRequestUpsertOne{
		create: _c,
	}
}

type (
	// SigningRequestUpsertOne is the builder for "upsert"-ing
	//  one SigningRequest node.
	SigningRequestUpsertOne struct {
		create *SigningRequestCreate
	}

	// SigningRequestUpsert is the "OnConflict" setter.
	SigningRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *SigningRequestUpsert) SetCreateBy(v uint32) *SigningRequestUpsert {
	u.Set(signingrequest.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateCreateBy() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *SigningRequestUpsert) AddCreateBy(v uint32) *SigningRequestUpsert {
	u.Add(signingrequest.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SigningRequestUpsert) ClearCreateBy() *SigningRequestUpsert {
	u.SetNull(signingrequest.FieldCreateBy)
	return u
}

// SetUpdateBy sets the "update_by" field.
func (u *SigningRequestUpsert) SetUpdateBy(v uint32) *SigningRequestUpsert {
	u.Set(signingrequest.FieldUpdateBy, v)
	return u
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateUpdateBy() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldUpdateBy)
	return u
}

// AddUpdateBy adds v to the "update_by" field.
func (u *SigningRequestUpsert) AddUpdateBy(v uint32) *SigningRequestUpsert {
	u.Add(signingrequest.FieldUpdateBy, v)
	return u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *SigningRequestUpsert) ClearUpdateBy() *SigningRequestUpsert {
	u.SetNull(signingrequest.FieldUpdateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SigningRequestUpsert) SetUpdateTime(v time.Time) *SigningRequestUpsert {
	u.Set(signingrequest.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateUpdateTime() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SigningRequestUpsert) ClearUpdateTime() *SigningRequestUpsert {
	u.SetNull(signingrequest.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *SigningRequestUpsert) SetDeleteTime(v time.Time) *SigningRequestUpsert {
	u.Set(signingrequest.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateDeleteTime() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SigningRequestUpsert) ClearDeleteTime() *SigningRequestUpsert {
	u.SetNull(signingrequest.FieldDeleteTime)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *SigningRequestUpsert) SetTemplateID(v string) *SigningRequestUpsert {
	u.Set(signingrequest.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateTemplateID() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldTemplateID)
	return u
}

// SetName sets the "name" field.
func (u *SigningRequestUpsert) SetName(v string) *SigningRequestUpsert {
	u.Set(signingrequest.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateName() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldName)
	return u
}

// SetStatus sets the "status" field.
func (u *SigningRequestUpsert) SetStatus(v signingrequest.Status) *SigningRequestUpsert {
	u.Set(signingrequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateStatus() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldStatus)
	return u
}

// SetSigningType sets the "signing_type" field.
func (u *SigningRequestUpsert) SetSigningType(v signingrequest.SigningType) *SigningRequestUpsert {
	u.Set(signingrequest.FieldSigningType, v)
	return u
}

// UpdateSigningType sets the "signing_type" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateSigningType() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldSigningType)
	return u
}

// SetOriginalFileKey sets the "original_file_key" field.
func (u *SigningRequestUpsert) SetOriginalFileKey(v string) *SigningRequestUpsert {
	u.Set(signingrequest.FieldOriginalFileKey, v)
	return u
}

// UpdateOriginalFileKey sets the "original_file_key" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateOriginalFileKey() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldOriginalFileKey)
	return u
}

// ClearOriginalFileKey clears the value of the "original_file_key" field.
func (u *SigningRequestUpsert) ClearOriginalFileKey() *SigningRequestUpsert {
	u.SetNull(signingrequest.FieldOriginalFileKey)
	return u
}

// SetSignedFileKey sets the "signed_file_key" field.
func (u *SigningRequestUpsert) SetSignedFileKey(v string) *SigningRequestUpsert {
	u.Set(signingrequest.FieldSignedFileKey, v)
	return u
}

// UpdateSignedFileKey sets the "signed_file_key" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateSignedFileKey() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldSignedFileKey)
	return u
}

// ClearSignedFileKey clears the value of the "signed_file_key" field.
func (u *SigningRequestUpsert) ClearSignedFileKey() *SigningRequestUpsert {
	u.SetNull(signingrequest.FieldSignedFileKey)
	return u
}

// SetFieldValues sets the "field_values" field.
func (u *SigningRequestUpsert) SetFieldValues(v []schema.SigningFieldValueDef) *SigningRequestUpsert {
	u.Set(signingrequest.FieldFieldValues, v)
	return u
}

// UpdateFieldValues sets the "field_values" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateFieldValues() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldFieldValues)
	return u
}

// ClearFieldValues clears the value of the "field_values" field.
func (u *SigningRequestUpsert) ClearFieldValues() *SigningRequestUpsert {
	u.SetNull(signingrequest.FieldFieldValues)
	return u
}

// SetMessage sets the "message" field.
func (u *SigningRequestUpsert) SetMessage(v string) *SigningRequestUpsert {
	u.Set(signingrequest.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateMessage() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *SigningRequestUpsert) ClearMessage() *SigningRequestUpsert {
	u.SetNull(signingrequest.FieldMessage)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *SigningRequestUpsert) SetExpiresAt(v time.Time) *SigningRequestUpsert {
	u.Set(signingrequest.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SigningRequestUpsert) UpdateExpiresAt() *SigningRequestUpsert {
	u.SetExcluded(signingrequest.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SigningRequestUpsert) ClearExpiresAt() *SigningRequestUpsert {
	u.SetNull(signingrequest.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SigningRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(signingrequest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SigningRequestUpsertOne) UpdateNewValues() *SigningRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(signingrequest.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(signingrequest.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(signingrequest.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SigningRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SigningRequestUpsertOne) Ignore() *SigningRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SigningRequestUpsertOne) DoNothing() *SigningRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SigningRequestCreate.OnConflict
// documentation for more info.
func (u *SigningRequestUpsertOne) Update(set func(*SigningRequestUpsert)) *SigningRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SigningRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SigningRequestUpsertOne) SetCreateBy(v uint32) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SigningRequestUpsertOne) AddCreateBy(v uint32) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateCreateBy() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SigningRequestUpsertOne) ClearCreateBy() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *SigningRequestUpsertOne) SetUpdateBy(v uint32) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *SigningRequestUpsertOne) AddUpdateBy(v uint32) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateUpdateBy() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *SigningRequestUpsertOne) ClearUpdateBy() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SigningRequestUpsertOne) SetUpdateTime(v time.Time) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateUpdateTime() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SigningRequestUpsertOne) ClearUpdateTime() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SigningRequestUpsertOne) SetDeleteTime(v time.Time) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateDeleteTime() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SigningRequestUpsertOne) ClearDeleteTime() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearDeleteTime()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *SigningRequestUpsertOne) SetTemplateID(v string) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateTemplateID() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateTemplateID()
	})
}

// SetName sets the "name" field.
func (u *SigningRequestUpsertOne) SetName(v string) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateName() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *SigningRequestUpsertOne) SetStatus(v signingrequest.Status) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateStatus() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetSigningType sets the "signing_type" field.
func (u *SigningRequestUpsertOne) SetSigningType(v signingrequest.SigningType) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetSigningType(v)
	})
}

// UpdateSigningType sets the "signing_type" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateSigningType() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateSigningType()
	})
}

// SetOriginalFileKey sets the "original_file_key" field.
func (u *SigningRequestUpsertOne) SetOriginalFileKey(v string) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetOriginalFileKey(v)
	})
}

// UpdateOriginalFileKey sets the "original_file_key" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateOriginalFileKey() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateOriginalFileKey()
	})
}

// ClearOriginalFileKey clears the value of the "original_file_key" field.
func (u *SigningRequestUpsertOne) ClearOriginalFileKey() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearOriginalFileKey()
	})
}

// SetSignedFileKey sets the "signed_file_key" field.
func (u *SigningRequestUpsertOne) SetSignedFileKey(v string) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetSignedFileKey(v)
	})
}

// UpdateSignedFileKey sets the "signed_file_key" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateSignedFileKey() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateSignedFileKey()
	})
}

// ClearSignedFileKey clears the value of the "signed_file_key" field.
func (u *SigningRequestUpsertOne) ClearSignedFileKey() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearSignedFileKey()
	})
}

// SetFieldValues sets the "field_values" field.
func (u *SigningRequestUpsertOne) SetFieldValues(v []schema.SigningFieldValueDef) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetFieldValues(v)
	})
}

// UpdateFieldValues sets the "field_values" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateFieldValues() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateFieldValues()
	})
}

// ClearFieldValues clears the value of the "field_values" field.
func (u *SigningRequestUpsertOne) ClearFieldValues() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearFieldValues()
	})
}

// SetMessage sets the "message" field.
func (u *SigningRequestUpsertOne) SetMessage(v string) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateMessage() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *SigningRequestUpsertOne) ClearMessage() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearMessage()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SigningRequestUpsertOne) SetExpiresAt(v time.Time) *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SigningRequestUpsertOne) UpdateExpiresAt() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SigningRequestUpsertOne) ClearExpiresAt() *SigningRequestUpsertOne {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *SigningRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SigningRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SigningRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SigningRequestUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SigningRequestUpsertOne.ID is not supported by MySQL driver. Use SigningRequestUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SigningRequestUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SigningRequestCreateBulk is the builder for creating many SigningRequest entities in bulk.
type SigningRequestCreateBulk struct {
	config
	err      error
	builders []*SigningRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the SigningRequest entities in the database.
func (_c *SigningRequestCreateBulk) Save(ctx context.Context) ([]*SigningRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SigningRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SigningRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SigningRequestCreateBulk) SaveX(ctx context.Context) []*SigningRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SigningRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SigningRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SigningRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SigningRequestUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SigningRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *SigningRequestUpsertBulk {
	_c.conflict = opts
	return &SigningRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SigningRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SigningRequestCreateBulk) OnConflictColumns(columns ...string) *SigningRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SigningRequestUpsertBulk{
		create: _c,
	}
}

// SigningRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of SigningRequest nodes.
type SigningRequestUpsertBulk struct {
	create *SigningRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SigningRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(signingrequest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SigningRequestUpsertBulk) UpdateNewValues() *SigningRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(signingrequest.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(signingrequest.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(signingrequest.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SigningRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SigningRequestUpsertBulk) Ignore() *SigningRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SigningRequestUpsertBulk) DoNothing() *SigningRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SigningRequestCreateBulk.OnConflict
// documentation for more info.
func (u *SigningRequestUpsertBulk) Update(set func(*SigningRequestUpsert)) *SigningRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SigningRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SigningRequestUpsertBulk) SetCreateBy(v uint32) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SigningRequestUpsertBulk) AddCreateBy(v uint32) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateCreateBy() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SigningRequestUpsertBulk) ClearCreateBy() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *SigningRequestUpsertBulk) SetUpdateBy(v uint32) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *SigningRequestUpsertBulk) AddUpdateBy(v uint32) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateUpdateBy() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *SigningRequestUpsertBulk) ClearUpdateBy() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SigningRequestUpsertBulk) SetUpdateTime(v time.Time) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateUpdateTime() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SigningRequestUpsertBulk) ClearUpdateTime() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SigningRequestUpsertBulk) SetDeleteTime(v time.Time) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateDeleteTime() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SigningRequestUpsertBulk) ClearDeleteTime() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearDeleteTime()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *SigningRequestUpsertBulk) SetTemplateID(v string) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateTemplateID() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateTemplateID()
	})
}

// SetName sets the "name" field.
func (u *SigningRequestUpsertBulk) SetName(v string) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateName() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *SigningRequestUpsertBulk) SetStatus(v signingrequest.Status) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateStatus() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetSigningType sets the "signing_type" field.
func (u *SigningRequestUpsertBulk) SetSigningType(v signingrequest.SigningType) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetSigningType(v)
	})
}

// UpdateSigningType sets the "signing_type" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateSigningType() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateSigningType()
	})
}

// SetOriginalFileKey sets the "original_file_key" field.
func (u *SigningRequestUpsertBulk) SetOriginalFileKey(v string) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetOriginalFileKey(v)
	})
}

// UpdateOriginalFileKey sets the "original_file_key" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateOriginalFileKey() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateOriginalFileKey()
	})
}

// ClearOriginalFileKey clears the value of the "original_file_key" field.
func (u *SigningRequestUpsertBulk) ClearOriginalFileKey() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearOriginalFileKey()
	})
}

// SetSignedFileKey sets the "signed_file_key" field.
func (u *SigningRequestUpsertBulk) SetSignedFileKey(v string) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetSignedFileKey(v)
	})
}

// UpdateSignedFileKey sets the "signed_file_key" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateSignedFileKey() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateSignedFileKey()
	})
}

// ClearSignedFileKey clears the value of the "signed_file_key" field.
func (u *SigningRequestUpsertBulk) ClearSignedFileKey() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearSignedFileKey()
	})
}

// SetFieldValues sets the "field_values" field.
func (u *SigningRequestUpsertBulk) SetFieldValues(v []schema.SigningFieldValueDef) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetFieldValues(v)
	})
}

// UpdateFieldValues sets the "field_values" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateFieldValues() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateFieldValues()
	})
}

// ClearFieldValues clears the value of the "field_values" field.
func (u *SigningRequestUpsertBulk) ClearFieldValues() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearFieldValues()
	})
}

// SetMessage sets the "message" field.
func (u *SigningRequestUpsertBulk) SetMessage(v string) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateMessage() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *SigningRequestUpsertBulk) ClearMessage() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearMessage()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SigningRequestUpsertBulk) SetExpiresAt(v time.Time) *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SigningRequestUpsertBulk) UpdateExpiresAt() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SigningRequestUpsertBulk) ClearExpiresAt() *SigningRequestUpsertBulk {
	return u.Update(func(s *SigningRequestUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *SigningRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SigningRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SigningRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SigningRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
