// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingtemplate"
)

// SigningTemplateUpdate is the builder for updating SigningTemplate entities.
type SigningTemplateUpdate struct {
	config
	hooks     []Hook
	mutation  *SigningTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SigningTemplateUpdate builder.
func (_u *SigningTemplateUpdate) Where(ps ...predicate.SigningTemplate) *SigningTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *SigningTemplateUpdate) SetCreateBy(v uint32) *SigningTemplateUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SigningTemplateUpdate) SetNillableCreateBy(v *uint32) *SigningTemplateUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SigningTemplateUpdate) AddCreateBy(v int32) *SigningTemplateUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SigningTemplateUpdate) ClearCreateBy() *SigningTemplateUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *SigningTemplateUpdate) SetUpdateBy(v uint32) *SigningTemplateUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *SigningTemplateUpdate) SetNillableUpdateBy(v *uint32) *SigningTemplateUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *SigningTemplateUpdate) AddUpdateBy(v int32) *SigningTemplateUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *SigningTemplateUpdate) ClearUpdateBy() *SigningTemplateUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SigningTemplateUpdate) SetUpdateTime(v time.Time) *SigningTemplateUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SigningTemplateUpdate) SetNillableUpdateTime(v *time.Time) *SigningTemplateUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SigningTemplateUpdate) ClearUpdateTime() *SigningTemplateUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SigningTemplateUpdate) SetDeleteTime(v time.Time) *SigningTemplateUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SigningTemplateUpdate) SetNillableDeleteTime(v *time.Time) *SigningTemplateUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SigningTemplateUpdate) ClearDeleteTime() *SigningTemplateUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *SigningTemplateUpdate) SetName(v string) *SigningTemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SigningTemplateUpdate) SetNillableName(v *string) *SigningTemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SigningTemplateUpdate) SetDescription(v string) *SigningTemplateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SigningTemplateUpdate) SetNillableDescription(v *string) *SigningTemplateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SigningTemplateUpdate) ClearDescription() *SigningTemplateUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetFileKey sets the "file_key" field.
func (_u *SigningTemplateUpdate) SetFileKey(v string) *SigningTemplateUpdate {
	_u.mutation.SetFileKey(v)
	return _u
}

// SetNillableFileKey sets the "file_key" field if the given value is not nil.
func (_u *SigningTemplateUpdate) SetNillableFileKey(v *string) *SigningTemplateUpdate {
	if v != nil {
		_u.SetFileKey(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *SigningTemplateUpdate) SetFileName(v string) *SigningTemplateUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *SigningTemplateUpdate) SetNillableFileName(v *string) *SigningTemplateUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *SigningTemplateUpdate) SetFileSize(v int64) *SigningTemplateUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *SigningTemplateUpdate) SetNillableFileSize(v *int64) *SigningTemplateUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *SigningTemplateUpdate) AddFileSize(v int64) *SigningTemplateUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetFields sets the "fields" field.
func (_u *SigningTemplateUpdate) SetFields(v []schema.SigningTemplateFieldDef) *SigningTemplateUpdate {
	_u.mutation.SetFields(v)
	return _u
}

// AppendFields appends value to the "fields" field.
func (_u *SigningTemplateUpdate) AppendFields(v []schema.SigningTemplateFieldDef) *SigningTemplateUpdate {
	_u.mutation.AppendFields(v)
	return _u
}

// ClearFields clears the value of the "fields" field.
func (_u *SigningTemplateUpdate) ClearFields() *SigningTemplateUpdate {
	_u.mutation.ClearFields()
	return _u
}

// Mutation returns the SigningTemplateMutation object of the builder.
func (_u *SigningTemplateUpdate) Mutation() *SigningTemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SigningTemplateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SigningTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SigningTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SigningTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SigningTemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := signingtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := signingtemplate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileKey(); ok {
		if err := signingtemplate.FileKeyValidator(v); err != nil {
			return &ValidationError{Name: "file_key", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.file_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := signingtemplate.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.file_name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SigningTemplateUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SigningTemplateUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SigningTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(signingtemplate.Table, signingtemplate.Columns, sqlgraph.NewFieldSpec(signingtemplate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(signingtemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(signingtemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(signingtemplate.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(signingtemplate.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(signingtemplate.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(signingtemplate.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(signingtemplate.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(signingtemplate.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(signingtemplate.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(signingtemplate.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(signingtemplate.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(signingtemplate.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(signingtemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(signingtemplate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(signingtemplate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.FileKey(); ok {
		_spec.SetField(signingtemplate.FieldFileKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(signingtemplate.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(signingtemplate.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(signingtemplate.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetFields(); ok {
		_spec.SetField(signingtemplate.FieldFields, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFields(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, signingtemplate.FieldFields, value)
		})
	}
	if _u.mutation.FieldsCleared() {
		_spec.ClearField(signingtemplate.FieldFields, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signingtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SigningTemplateUpdateOne is the builder for updating a single SigningTemplate entity.
type SigningTemplateUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SigningTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *SigningTemplateUpdateOne) SetCreateBy(v uint32) *SigningTemplateUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SigningTemplateUpdateOne) SetNillableCreateBy(v *uint32) *SigningTemplateUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SigningTemplateUpdateOne) AddCreateBy(v int32) *SigningTemplateUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SigningTemplateUpdateOne) ClearCreateBy() *SigningTemplateUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *SigningTemplateUpdateOne) SetUpdateBy(v uint32) *SigningTemplateUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *SigningTemplateUpdateOne) SetNillableUpdateBy(v *uint32) *SigningTemplateUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *SigningTemplateUpdateOne) AddUpdateBy(v int32) *SigningTemplateUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *SigningTemplateUpdateOne) ClearUpdateBy() *SigningTemplateUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SigningTemplateUpdateOne) SetUpdateTime(v time.Time) *SigningTemplateUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SigningTemplateUpdateOne) SetNillableUpdateTime(v *time.Time) *SigningTemplateUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SigningTemplateUpdateOne) ClearUpdateTime() *SigningTemplateUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SigningTemplateUpdateOne) SetDeleteTime(v time.Time) *SigningTemplateUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SigningTemplateUpdateOne) SetNillableDeleteTime(v *time.Time) *SigningTemplateUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SigningTemplateUpdateOne) ClearDeleteTime() *SigningTemplateUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *SigningTemplateUpdateOne) SetName(v string) *SigningTemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SigningTemplateUpdateOne) SetNillableName(v *string) *SigningTemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SigningTemplateUpdateOne) SetDescription(v string) *SigningTemplateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SigningTemplateUpdateOne) SetNillableDescription(v *string) *SigningTemplateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SigningTemplateUpdateOne) ClearDescription() *SigningTemplateUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetFileKey sets the "file_key" field.
func (_u *SigningTemplateUpdateOne) SetFileKey(v string) *SigningTemplateUpdateOne {
	_u.mutation.SetFileKey(v)
	return _u
}

// SetNillableFileKey sets the "file_key" field if the given value is not nil.
func (_u *SigningTemplateUpdateOne) SetNillableFileKey(v *string) *SigningTemplateUpdateOne {
	if v != nil {
		_u.SetFileKey(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *SigningTemplateUpdateOne) SetFileName(v string) *SigningTemplateUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *SigningTemplateUpdateOne) SetNillableFileName(v *string) *SigningTemplateUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *SigningTemplateUpdateOne) SetFileSize(v int64) *SigningTemplateUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *SigningTemplateUpdateOne) SetNillableFileSize(v *int64) *SigningTemplateUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *SigningTemplateUpdateOne) AddFileSize(v int64) *SigningTemplateUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetFields sets the "fields" field.
func (_u *SigningTemplateUpdateOne) SetFields(v []schema.SigningTemplateFieldDef) *SigningTemplateUpdateOne {
	_u.mutation.SetFields(v)
	return _u
}

// AppendFields appends value to the "fields" field.
func (_u *SigningTemplateUpdateOne) AppendFields(v []schema.SigningTemplateFieldDef) *SigningTemplateUpdateOne {
	_u.mutation.AppendFields(v)
	return _u
}

// ClearFields clears the value of the "fields" field.
func (_u *SigningTemplateUpdateOne) ClearFields() *SigningTemplateUpdateOne {
	_u.mutation.ClearFields()
	return _u
}

// Mutation returns the SigningTemplateMutation object of the builder.
func (_u *SigningTemplateUpdateOne) Mutation() *SigningTemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the SigningTemplateUpdate builder.
func (_u *SigningTemplateUpdateOne) Where(ps ...predicate.SigningTemplate) *SigningTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SigningTemplateUpdateOne) Select(field string, fields ...string) *SigningTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SigningTemplate entity.
func (_u *SigningTemplateUpdateOne) Save(ctx context.Context) (*SigningTemplate, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SigningTemplateUpdateOne) SaveX(ctx context.Context) *SigningTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SigningTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SigningTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SigningTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := signingtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := signingtemplate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileKey(); ok {
		if err := signingtemplate.FileKeyValidator(v); err != nil {
			return &ValidationError{Name: "file_key", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.file_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := signingtemplate.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.file_name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SigningTemplateUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SigningTemplateUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SigningTemplateUpdateOne) sqlSave(ctx context.Context) (_node *SigningTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(signingtemplate.Table, signingtemplate.Columns, sqlgraph.NewFieldSpec(signingtemplate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SigningTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signingtemplate.FieldID)
		for _, f := range fields {
			if !signingtemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != signingtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(signingtemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(signingtemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(signingtemplate.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(signingtemplate.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(signingtemplate.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(signingtemplate.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(signingtemplate.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(signingtemplate.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(signingtemplate.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(signingtemplate.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(signingtemplate.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(signingtemplate.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(signingtemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(signingtemplate.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(signingtemplate.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.FileKey(); ok {
		_spec.SetField(signingtemplate.FieldFileKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(signingtemplate.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(signingtemplate.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(signingtemplate.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetFields(); ok {
		_spec.SetField(signingtemplate.FieldFields, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFields(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, signingtemplate.FieldFields, value)
		})
	}
	if _u.mutation.FieldsCleared() {
		_spec.ClearField(signingtemplate.FieldFields, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SigningTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signingtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
