// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingtemplate"
)

// SigningTemplateCreate is the builder for creating a SigningTemplate entity.
type SigningTemplateCreate struct {
	config
	mutation *SigningTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *SigningTemplateCreate) SetCreateBy(v uint32) *SigningTemplateCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *SigningTemplateCreate) SetNillableCreateBy(v *uint32) *SigningTemplateCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *SigningTemplateCreate) SetUpdateBy(v uint32) *SigningTemplateCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *SigningTemplateCreate) SetNillableUpdateBy(v *uint32) *SigningTemplateCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *SigningTemplateCreate) SetCreateTime(v time.Time) *SigningTemplateCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SigningTemplateCreate) SetNillableCreateTime(v *time.Time) *SigningTemplateCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SigningTemplateCreate) SetUpdateTime(v time.Time) *SigningTemplateCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SigningTemplateCreate) SetNillableUpdateTime(v *time.Time) *SigningTemplateCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *SigningTemplateCreate) SetDeleteTime(v time.Time) *SigningTemplateCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *SigningTemplateCreate) SetNillableDeleteTime(v *time.Time) *SigningTemplateCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *SigningTemplateCreate) SetTenantID(v uint32) *SigningTemplateCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *SigningTemplateCreate) SetNillableTenantID(v *uint32) *SigningTemplateCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SigningTemplateCreate) SetName(v string) *SigningTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SigningTemplateCreate) SetDescription(v string) *SigningTemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SigningTemplateCreate) SetNillableDescription(v *string) *SigningTemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetFileKey sets the "file_key" field.
func (_c *SigningTemplateCreate) SetFileKey(v string) *SigningTemplateCreate {
	_c.mutation.SetFileKey(v)
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *SigningTemplateCreate) SetFileName(v string) *SigningTemplateCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *SigningTemplateCreate) SetFileSize(v int64) *SigningTemplateCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_c *SigningTemplateCreate) SetNillableFileSize(v *int64) *SigningTemplateCreate {
	if v != nil {
		_c.SetFileSize(*v)
	}
	return _c
}

// SetFields sets the "fields" field.
func (_c *SigningTemplateCreate) SetFields(v []schema.SigningTemplateFieldDef) *SigningTemplateCreate {
	_c.mutation.SetFields(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SigningTemplateCreate) SetID(v string) *SigningTemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SigningTemplateMutation object of the builder.
func (_c *SigningTemplateCreate) Mutation() *SigningTemplateMutation {
	return _c.mutation
}

// Save creates the SigningTemplate in the database.
func (_c *SigningTemplateCreate) Save(ctx context.Context) (*SigningTemplate, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SigningTemplateCreate) SaveX(ctx context.Context) *SigningTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SigningTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SigningTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SigningTemplateCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := signingtemplate.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		v := signingtemplate.DefaultFileSize
		_c.mutation.SetFileSize(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SigningTemplateCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SigningTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := signingtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := signingtemplate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileKey(); !ok {
		return &ValidationError{Name: "file_key", err: errors.New(`ent: missing required field "SigningTemplate.file_key"`)}
	}
	if v, ok := _c.mutation.FileKey(); ok {
		if err := signingtemplate.FileKeyValidator(v); err != nil {
			return &ValidationError{Name: "file_key", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.file_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "SigningTemplate.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := signingtemplate.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "SigningTemplate.file_size"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := signingtemplate.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SigningTemplate.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SigningTemplateCreate) sqlSave(ctx context.Context) (*SigningTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SigningTemplate.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SigningTemplateCreate) createSpec() (*SigningTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &SigningTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(signingtemplate.Table, sqlgraph.NewFieldSpec(signingtemplate.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(signingtemplate.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(signingtemplate.FieldUpdateBy, field.TypeUint32, value)
		_node.UpdateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(signingtemplate.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(signingtemplate.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(signingtemplate.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(signingtemplate.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(signingtemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(signingtemplate.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.FileKey(); ok {
		_spec.SetField(signingtemplate.FieldFileKey, field.TypeString, value)
		_node.FileKey = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(signingtemplate.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(signingtemplate.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.GetFields(); ok {
		_spec.SetField(signingtemplate.FieldFields, field.TypeJSON, value)
		_node.Fields = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SigningTemplate.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SigningTemplateUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SigningTemplateCreate) OnConflict(opts ...sql.ConflictOption) *SigningTemplateUpsertOne {
	_c.conflict = opts
	return &SigningTemplateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SigningTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SigningTemplateCreate) OnConflictColumns(columns ...string) *SigningTemplateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SigningTemplateUpsertOne{
		create: _c,
	}
}

type (
	// SigningTemplateUpsertOne is the builder for "upsert"-ing
	//  one SigningTemplate node.
	SigningTemplateUpsertOne struct {
		create *SigningTemplateCreate
	}

	// SigningTemplateUpsert is the "OnConflict" setter.
	SigningTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *SigningTemplateUpsert) SetCreateBy(v uint32) *SigningTemplateUpsert {
	u.Set(signingtemplate.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SigningTemplateUpsert) UpdateCreateBy() *SigningTemplateUpsert {
	u.SetExcluded(signingtemplate.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *SigningTemplateUpsert) AddCreateBy(v uint32) *SigningTemplateUpsert {
	u.Add(signingtemplate.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SigningTemplateUpsert) ClearCreateBy() *SigningTemplateUpsert {
	u.SetNull(signingtemplate.FieldCreateBy)
	return u
}

// SetUpdateBy sets the "update_by" field.
func (u *SigningTemplateUpsert) SetUpdateBy(v uint32) *SigningTemplateUpsert {
	u.Set(signingtemplate.FieldUpdateBy, v)
	return u
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *SigningTemplateUpsert) UpdateUpdateBy() *SigningTemplateUpsert {
	u.SetExcluded(signingtemplate.FieldUpdateBy)
	return u
}

// AddUpdateBy adds v to the "update_by" field.
func (u *SigningTemplateUpsert) AddUpdateBy(v uint32) *SigningTemplateUpsert {
	u.Add(signingtemplate.FieldUpdateBy, v)
	return u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *SigningTemplateUpsert) ClearUpdateBy() *SigningTemplateUpsert {
	u.SetNull(signingtemplate.FieldUpdateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SigningTemplateUpsert) SetUpdateTime(v time.Time) *SigningTemplateUpsert {
	u.Set(signingtemplate.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SigningTemplateUpsert) UpdateUpdateTime() *SigningTemplateUpsert {
	u.SetExcluded(signingtemplate.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SigningTemplateUpsert) ClearUpdateTime() *SigningTemplateUpsert {
	u.SetNull(signingtemplate.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *SigningTemplateUpsert) SetDeleteTime(v time.Time) *SigningTemplateUpsert {
	u.Set(signingtemplate.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SigningTemplateUpsert) UpdateDeleteTime() *SigningTemplateUpsert {
	u.SetExcluded(signingtemplate.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SigningTemplateUpsert) ClearDeleteTime() *SigningTemplateUpsert {
	u.SetNull(signingtemplate.FieldDeleteTime)
	return u
}

// SetName sets the "name" field.
func (u *SigningTemplateUpsert) SetName(v string) *SigningTemplateUpsert {
	u.Set(signingtemplate.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SigningTemplateUpsert) UpdateName() *SigningTemplateUpsert {
	u.SetExcluded(signingtemplate.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *SigningTemplateUpsert) SetDescription(v string) *SigningTemplateUpsert {
	u.Set(signingtemplate.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SigningTemplateUpsert) UpdateDescription() *SigningTemplateUpsert {
	u.SetExcluded(signingtemplate.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SigningTemplateUpsert) ClearDescription() *SigningTemplateUpsert {
	u.SetNull(signingtemplate.FieldDescription)
	return u
}

// SetFileKey sets the "file_key" field.
func (u *SigningTemplateUpsert) SetFileKey(v string) *SigningTemplateUpsert {
	u.Set(signingtemplate.FieldFileKey, v)
	return u
}

// UpdateFileKey sets the "file_key" field to the value that was provided on create.
func (u *SigningTemplateUpsert) UpdateFileKey() *SigningTemplateUpsert {
	u.SetExcluded(signingtemplate.FieldFileKey)
	return u
}

// SetFileName sets the "file_name" field.
func (u *SigningTemplateUpsert) SetFileName(v string) *SigningTemplateUpsert {
	u.Set(signingtemplate.FieldFileName, v)
	return u
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *SigningTemplateUpsert) UpdateFileName() *SigningTemplateUpsert {
	u.SetExcluded(signingtemplate.FieldFileName)
	return u
}

// SetFileSize sets the "file_size" field.
func (u *SigningTemplateUpsert) SetFileSize(v int64) *SigningTemplateUpsert {
	u.Set(signingtemplate.FieldFileSize, v)
	return u
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *SigningTemplateUpsert) UpdateFileSize() *SigningTemplateUpsert {
	u.SetExcluded(signingtemplate.FieldFileSize)
	return u
}

// AddFileSize adds v to the "file_size" field.
func (u *SigningTemplateUpsert) AddFileSize(v int64) *SigningTemplateUpsert {
	u.Add(signingtemplate.FieldFileSize, v)
	return u
}

// SetFields sets the "fields" field.
func (u *SigningTemplateUpsert) SetFields(v []schema.SigningTemplateFieldDef) *SigningTemplateUpsert {
	u.Set(signingtemplate.FieldFields, v)
	return u
}

// UpdateFields sets the "fields" field to the value that was provided on create.
func (u *SigningTemplateUpsert) UpdateFields() *SigningTemplateUpsert {
	u.SetExcluded(signingtemplate.FieldFields)
	return u
}

// ClearFields clears the value of the "fields" field.
func (u *SigningTemplateUpsert) ClearFields() *SigningTemplateUpsert {
	u.SetNull(signingtemplate.FieldFields)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SigningTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(signingtemplate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SigningTemplateUpsertOne) UpdateNewValues() *SigningTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(signingtemplate.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(signingtemplate.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(signingtemplate.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SigningTemplate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SigningTemplateUpsertOne) Ignore() *SigningTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SigningTemplateUpsertOne) DoNothing() *SigningTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SigningTemplateCreate.OnConflict
// documentation for more info.
func (u *SigningTemplateUpsertOne) Update(set func(*SigningTemplateUpsert)) *SigningTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SigningTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SigningTemplateUpsertOne) SetCreateBy(v uint32) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SigningTemplateUpsertOne) AddCreateBy(v uint32) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SigningTemplateUpsertOne) UpdateCreateBy() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SigningTemplateUpsertOne) ClearCreateBy() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *SigningTemplateUpsertOne) SetUpdateBy(v uint32) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *SigningTemplateUpsertOne) AddUpdateBy(v uint32) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *SigningTemplateUpsertOne) UpdateUpdateBy() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *SigningTemplateUpsertOne) ClearUpdateBy() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SigningTemplateUpsertOne) SetUpdateTime(v time.Time) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SigningTemplateUpsertOne) UpdateUpdateTime() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SigningTemplateUpsertOne) ClearUpdateTime() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SigningTemplateUpsertOne) SetDeleteTime(v time.Time) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SigningTemplateUpsertOne) UpdateDeleteTime() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SigningTemplateUpsertOne) ClearDeleteTime() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *SigningTemplateUpsertOne) SetName(v string) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SigningTemplateUpsertOne) UpdateName() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SigningTemplateUpsertOne) SetDescription(v string) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SigningTemplateUpsertOne) UpdateDescription() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SigningTemplateUpsertOne) ClearDescription() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearDescription()
	})
}

// SetFileKey sets the "file_key" field.
func (u *SigningTemplateUpsertOne) SetFileKey(v string) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetFileKey(v)
	})
}

// UpdateFileKey sets the "file_key" field to the value that was provided on create.
func (u *SigningTemplateUpsertOne) UpdateFileKey() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateFileKey()
	})
}

// SetFileName sets the "file_name" field.
func (u *SigningTemplateUpsertOne) SetFileName(v string) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *SigningTemplateUpsertOne) UpdateFileName() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateFileName()
	})
}

// SetFileSize sets the "file_size" field.
func (u *SigningTemplateUpsertOne) SetFileSize(v int64) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *SigningTemplateUpsertOne) AddFileSize(v int64) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *SigningTemplateUpsertOne) UpdateFileSize() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateFileSize()
	})
}

// SetFields sets the "fields" field.
func (u *SigningTemplateUpsertOne) SetFields(v []schema.SigningTemplateFieldDef) *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetFields(v)
	})
}

// UpdateFields sets the "fields" field to the value that was provided on create.
func (u *SigningTemplateUpsertOne) UpdateFields() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateFields()
	})
}

// ClearFields clears the value of the "fields" field.
func (u *SigningTemplateUpsertOne) ClearFields() *SigningTemplateUpsertOne {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearFields()
	})
}

// Exec executes the query.
func (u *SigningTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SigningTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SigningTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SigningTemplateUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SigningTemplateUpsertOne.ID is not supported by MySQL driver. Use SigningTemplateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SigningTemplateUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SigningTemplateCreateBulk is the builder for creating many SigningTemplate entities in bulk.
type SigningTemplateCreateBulk struct {
	config
	err      error
	builders []*SigningTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the SigningTemplate entities in the database.
func (_c *SigningTemplateCreateBulk) Save(ctx context.Context) ([]*SigningTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SigningTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SigningTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SigningTemplateCreateBulk) SaveX(ctx context.Context) []*SigningTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SigningTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SigningTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SigningTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SigningTemplateUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SigningTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *SigningTemplateUpsertBulk {
	_c.conflict = opts
	return &SigningTemplateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SigningTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SigningTemplateCreateBulk) OnConflictColumns(columns ...string) *SigningTemplateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SigningTemplateUpsertBulk{
		create: _c,
	}
}

// SigningTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of SigningTemplate nodes.
type SigningTemplateUpsertBulk struct {
	create *SigningTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SigningTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(signingtemplate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SigningTemplateUpsertBulk) UpdateNewValues() *SigningTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(signingtemplate.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(signingtemplate.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(signingtemplate.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SigningTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SigningTemplateUpsertBulk) Ignore() *SigningTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SigningTemplateUpsertBulk) DoNothing() *SigningTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SigningTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *SigningTemplateUpsertBulk) Update(set func(*SigningTemplateUpsert)) *SigningTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SigningTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SigningTemplateUpsertBulk) SetCreateBy(v uint32) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SigningTemplateUpsertBulk) AddCreateBy(v uint32) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SigningTemplateUpsertBulk) UpdateCreateBy() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SigningTemplateUpsertBulk) ClearCreateBy() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *SigningTemplateUpsertBulk) SetUpdateBy(v uint32) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *SigningTemplateUpsertBulk) AddUpdateBy(v uint32) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *SigningTemplateUpsertBulk) UpdateUpdateBy() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *SigningTemplateUpsertBulk) ClearUpdateBy() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SigningTemplateUpsertBulk) SetUpdateTime(v time.Time) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SigningTemplateUpsertBulk) UpdateUpdateTime() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SigningTemplateUpsertBulk) ClearUpdateTime() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SigningTemplateUpsertBulk) SetDeleteTime(v time.Time) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SigningTemplateUpsertBulk) UpdateDeleteTime() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SigningTemplateUpsertBulk) ClearDeleteTime() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *SigningTemplateUpsertBulk) SetName(v string) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SigningTemplateUpsertBulk) UpdateName() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SigningTemplateUpsertBulk) SetDescription(v string) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SigningTemplateUpsertBulk) UpdateDescription() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SigningTemplateUpsertBulk) ClearDescription() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearDescription()
	})
}

// SetFileKey sets the "file_key" field.
func (u *SigningTemplateUpsertBulk) SetFileKey(v string) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetFileKey(v)
	})
}

// UpdateFileKey sets the "file_key" field to the value that was provided on create.
func (u *SigningTemplateUpsertBulk) UpdateFileKey() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateFileKey()
	})
}

// SetFileName sets the "file_name" field.
func (u *SigningTemplateUpsertBulk) SetFileName(v string) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *SigningTemplateUpsertBulk) UpdateFileName() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateFileName()
	})
}

// SetFileSize sets the "file_size" field.
func (u *SigningTemplateUpsertBulk) SetFileSize(v int64) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *SigningTemplateUpsertBulk) AddFileSize(v int64) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *SigningTemplateUpsertBulk) UpdateFileSize() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateFileSize()
	})
}

// SetFields sets the "fields" field.
func (u *SigningTemplateUpsertBulk) SetFields(v []schema.SigningTemplateFieldDef) *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.SetFields(v)
	})
}

// UpdateFields sets the "fields" field to the value that was provided on create.
func (u *SigningTemplateUpsertBulk) UpdateFields() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.UpdateFields()
	})
}

// ClearFields clears the value of the "fields" field.
func (u *SigningTemplateUpsertBulk) ClearFields() *SigningTemplateUpsertBulk {
	return u.Update(func(s *SigningTemplateUpsert) {
		s.ClearFields()
	})
}

// Exec executes the query.
func (u *SigningTemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SigningTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SigningTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SigningTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
