// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/signingrecipient"
)

// SigningRecipientDelete is the builder for deleting a SigningRecipient entity.
type SigningRecipientDelete struct {
	config
	hooks    []Hook
	mutation *SigningRecipientMutation
}

// Where appends a list predicates to the SigningRecipientDelete builder.
func (_d *SigningRecipientDelete) Where(ps ...predicate.SigningRecipient) *SigningRecipientDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SigningRecipientDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SigningRecipientDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SigningRecipientDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(signingrecipient.Table, sqlgraph.NewFieldSpec(signingrecipient.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SigningRecipientDeleteOne is the builder for deleting a single SigningRecipient entity.
type SigningRecipientDeleteOne struct {
	_d *SigningRecipientDelete
}

// Where appends a list predicates to the SigningRecipientDelete builder.
func (_d *SigningRecipientDeleteOne) Where(ps ...predicate.SigningRecipient) *SigningRecipientDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SigningRecipientDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{signingrecipient.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SigningRecipientDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
