// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// DocumentPermission is the predicate function for documentpermission builders.
type DocumentPermission func(*sql.Selector)

// SigningRecipient is the predicate function for signingrecipient builders.
type SigningRecipient func(*sql.Selector)

// SigningRequest is the predicate function for signingrequest builders.
type SigningRequest func(*sql.Selector)

// SigningTemplate is the predicate function for signingtemplate builders.
type SigningTemplate func(*sql.Selector)
