/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List categories in a parent category (or root if no parent specified) */
        get: operations["PaperlessCategoryService_ListCategories"];
        put?: never;
        /** @description Create a new category */
        post: operations["PaperlessCategoryService_CreateCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the category tree structure */
        get: operations["PaperlessCategoryService_GetCategoryTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a category by ID */
        get: operations["PaperlessCategoryService_GetCategory"];
        /** @description Update category metadata */
        put: operations["PaperlessCategoryService_UpdateCategory"];
        post?: never;
        /** @description Delete a category (must be empty by default) */
        delete: operations["PaperlessCategoryService_DeleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Move a category to a new parent */
        post: operations["PaperlessCategoryService_MoveCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List documents in a category */
        get: operations["PaperlessDocumentService_ListDocuments"];
        put?: never;
        /** @description Create a new document (upload) */
        post: operations["PaperlessDocumentService_CreateDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Batch delete documents */
        post: operations["PaperlessDocumentService_BatchDeleteDocuments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search documents across categories */
        get: operations["PaperlessDocumentService_SearchDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a document by ID (metadata only) */
        get: operations["PaperlessDocumentService_GetDocument"];
        /** @description Update document metadata */
        put: operations["PaperlessDocumentService_UpdateDocument"];
        post?: never;
        /** @description Delete a document */
        delete: operations["PaperlessDocumentService_DeleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download document content */
        get: operations["PaperlessDocumentService_DownloadDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{id}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get document download URL (presigned URL) */
        get: operations["PaperlessDocumentService_GetDocumentDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Move document to a different category */
        post: operations["PaperlessDocumentService_MoveDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List permissions on a resource */
        get: operations["PaperlessPermissionService_ListPermissions"];
        put?: never;
        /** @description Grant access to a resource */
        post: operations["PaperlessPermissionService_GrantAccess"];
        /** @description Revoke access from a resource */
        delete: operations["PaperlessPermissionService_RevokeAccess"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/permissions/accessible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List resources accessible by a subject */
        get: operations["PaperlessPermissionService_ListAccessibleResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/permissions/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Check if a subject has access to a resource */
        post: operations["PaperlessPermissionService_CheckAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/permissions/effective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get effective permissions for a subject on a resource */
        get: operations["PaperlessPermissionService_GetEffectivePermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request to batch delete documents */
        BatchDeleteDocumentsRequest: {
            ids: string[];
            /** @description Permanently delete (skip soft-delete and remove from storage) */
            permanent?: boolean;
        };
        BatchDeleteDocumentsResponse: {
            /**
             * Format: uint32
             * @description Number of documents successfully deleted
             */
            deletedCount?: number;
            /** @description IDs that failed to delete */
            failedIds?: string[];
        };
        /** @description Category entity */
        Category: {
            id?: string;
            /** Format: uint32 */
            tenantId?: number;
            parentId?: string;
            name?: string;
            path?: string;
            description?: string;
            /** Format: int32 */
            depth?: number;
            /** Format: int32 */
            sortOrder?: number;
            /** Format: int32 */
            documentCount?: number;
            /** Format: int32 */
            subcategoryCount?: number;
            /** Format: date-time */
            createTime?: string;
            /** Format: date-time */
            updateTime?: string;
            /** Format: uint32 */
            createdBy?: number;
        };
        /** @description Category tree node */
        CategoryTreeNode: {
            category?: components["schemas"]["Category"];
            children?: components["schemas"]["CategoryTreeNode"][];
        };
        /** @description Request to check access */
        CheckAccessRequest: {
            /** @description User ID to check */
            userId: string;
            /**
             * Format: enum
             * @description Resource type
             * @enum {string}
             */
            resourceType: "RESOURCE_TYPE_UNSPECIFIED" | "RESOURCE_TYPE_CATEGORY" | "RESOURCE_TYPE_DOCUMENT";
            /** @description Resource ID */
            resourceId: string;
            /**
             * Format: enum
             * @description Permission to check
             * @enum {string}
             */
            permission: "PERMISSION_UNSPECIFIED" | "PERMISSION_READ" | "PERMISSION_WRITE" | "PERMISSION_DELETE" | "PERMISSION_SHARE" | "PERMISSION_DOWNLOAD";
        };
        CheckAccessResponse: {
            allowed?: boolean;
            reason?: string;
        };
        /** @description Request to create a category */
        CreateCategoryRequest: {
            /** @description Parent category ID (null for root-level category) */
            parentId?: string;
            /** @description Category name */
            name: string;
            /** @description Optional description */
            description?: string;
            /**
             * Format: int32
             * @description Sort order (lower numbers appear first)
             */
            sortOrder?: number;
        };
        CreateCategoryResponse: {
            category?: components["schemas"]["Category"];
        };
        /** @description Request to create a document */
        CreateDocumentRequest: {
            /** @description Category ID (null for root-level) */
            categoryId?: string;
            /** @description Document name (display name) */
            name: string;
            /** @description Description */
            description?: string;
            /** @description Original file name */
            fileName: string;
            /**
             * Format: bytes
             * @description File content (base64 encoded for non-streaming)
             */
            fileContent: string;
            /** @description MIME type (optional - will be detected if not provided) */
            mimeType?: string;
            /** @description Custom tags */
            tags?: {
                [key: string]: string;
            };
            /**
             * Format: enum
             * @description Document source (default: UPLOAD)
             * @enum {string}
             */
            source?: "DOCUMENT_SOURCE_UNSPECIFIED" | "DOCUMENT_SOURCE_UPLOAD" | "DOCUMENT_SOURCE_EMAIL";
        };
        CreateDocumentResponse: {
            document?: components["schemas"]["Document"];
        };
        /** @description Document entity */
        Document: {
            id?: string;
            /** Format: uint32 */
            tenantId?: number;
            categoryId?: string;
            categoryPath?: string;
            name?: string;
            description?: string;
            fileKey?: string;
            fileName?: string;
            fileSize?: string;
            mimeType?: string;
            checksum?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "DOCUMENT_STATUS_UNSPECIFIED" | "DOCUMENT_STATUS_ACTIVE" | "DOCUMENT_STATUS_ARCHIVED" | "DOCUMENT_STATUS_DELETED";
            /**
             * Format: enum
             * @enum {string}
             */
            source?: "DOCUMENT_SOURCE_UNSPECIFIED" | "DOCUMENT_SOURCE_UPLOAD" | "DOCUMENT_SOURCE_EMAIL";
            tags?: {
                [key: string]: string;
            };
            /** Format: date-time */
            createTime?: string;
            /** Format: date-time */
            updateTime?: string;
            /** Format: uint32 */
            createdBy?: number;
            /** Format: uint32 */
            updatedBy?: number;
        };
        DownloadDocumentResponse: {
            /**
             * Format: bytes
             * @description File content
             */
            content?: string;
            /** @description Original file name */
            fileName?: string;
            /** @description MIME type */
            mimeType?: string;
            /** @description File size */
            fileSize?: string;
        };
        GetCategoryResponse: {
            category?: components["schemas"]["Category"];
        };
        GetCategoryTreeResponse: {
            roots?: components["schemas"]["CategoryTreeNode"][];
        };
        GetDocumentDownloadUrlResponse: {
            url?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        GetDocumentResponse: {
            document?: components["schemas"]["Document"];
        };
        GetEffectivePermissionsResponse: {
            permissions?: ("PERMISSION_UNSPECIFIED" | "PERMISSION_READ" | "PERMISSION_WRITE" | "PERMISSION_DELETE" | "PERMISSION_SHARE" | "PERMISSION_DOWNLOAD")[];
            /**
             * Format: enum
             * @enum {string}
             */
            highestRelation?: "RELATION_UNSPECIFIED" | "RELATION_OWNER" | "RELATION_EDITOR" | "RELATION_VIEWER" | "RELATION_SHARER";
        };
        /** @description Request to grant access */
        GrantAccessRequest: {
            /**
             * Format: enum
             * @description Resource type
             * @enum {string}
             */
            resourceType: "RESOURCE_TYPE_UNSPECIFIED" | "RESOURCE_TYPE_CATEGORY" | "RESOURCE_TYPE_DOCUMENT";
            /** @description Resource ID */
            resourceId: string;
            /**
             * Format: enum
             * @description Relation to grant
             * @enum {string}
             */
            relation: "RELATION_UNSPECIFIED" | "RELATION_OWNER" | "RELATION_EDITOR" | "RELATION_VIEWER" | "RELATION_SHARER";
            /**
             * Format: enum
             * @description Subject type
             * @enum {string}
             */
            subjectType: "SUBJECT_TYPE_UNSPECIFIED" | "SUBJECT_TYPE_USER" | "SUBJECT_TYPE_ROLE" | "SUBJECT_TYPE_TENANT";
            /** @description Subject ID */
            subjectId: string;
            /**
             * Format: date-time
             * @description Optional expiration time
             */
            expiresAt?: string;
        };
        GrantAccessResponse: {
            permission?: components["schemas"]["PermissionTuple"];
        };
        ListAccessibleResourcesResponse: {
            resourceIds?: string[];
            /** Format: uint32 */
            total?: number;
        };
        ListCategoriesResponse: {
            categories?: components["schemas"]["Category"][];
            /** Format: uint32 */
            total?: number;
        };
        ListDocumentsResponse: {
            documents?: components["schemas"]["Document"][];
            /** Format: uint32 */
            total?: number;
        };
        ListPermissionsResponse: {
            permissions?: components["schemas"]["PermissionTuple"][];
            /** Format: uint32 */
            total?: number;
        };
        /** @description Request to move a category */
        MoveCategoryRequest: {
            id: string;
            /** @description New parent category ID (null to move to root) */
            newParentId?: string;
        };
        MoveCategoryResponse: {
            category?: components["schemas"]["Category"];
        };
        /** @description Request to move a document */
        MoveDocumentRequest: {
            id: string;
            /** @description New category ID (null to move to root) */
            newCategoryId?: string;
        };
        MoveDocumentResponse: {
            document?: components["schemas"]["Document"];
        };
        /** @description Permission tuple entity */
        PermissionTuple: {
            /** Format: uint32 */
            id?: number;
            /** Format: uint32 */
            tenantId?: number;
            /**
             * Format: enum
             * @enum {string}
             */
            resourceType?: "RESOURCE_TYPE_UNSPECIFIED" | "RESOURCE_TYPE_CATEGORY" | "RESOURCE_TYPE_DOCUMENT";
            resourceId?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            relation?: "RELATION_UNSPECIFIED" | "RELATION_OWNER" | "RELATION_EDITOR" | "RELATION_VIEWER" | "RELATION_SHARER";
            /**
             * Format: enum
             * @enum {string}
             */
            subjectType?: "SUBJECT_TYPE_UNSPECIFIED" | "SUBJECT_TYPE_USER" | "SUBJECT_TYPE_ROLE" | "SUBJECT_TYPE_TENANT";
            subjectId?: string;
            /** Format: uint32 */
            grantedBy?: number;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            createTime?: string;
        };
        SearchDocumentsResponse: {
            documents?: components["schemas"]["Document"][];
            /** Format: uint32 */
            total?: number;
        };
        /** @description Request to update a category */
        UpdateCategoryRequest: {
            id: string;
            /** @description New name (optional) */
            name?: string;
            /** @description New description (optional) */
            description?: string;
            /**
             * Format: int32
             * @description New sort order (optional)
             */
            sortOrder?: number;
        };
        UpdateCategoryResponse: {
            category?: components["schemas"]["Category"];
        };
        /** @description Request to update document metadata */
        UpdateDocumentRequest: {
            id: string;
            /** @description New name */
            name?: string;
            /** @description New description */
            description?: string;
            /**
             * Format: enum
             * @description New status
             * @enum {string}
             */
            status?: "DOCUMENT_STATUS_UNSPECIFIED" | "DOCUMENT_STATUS_ACTIVE" | "DOCUMENT_STATUS_ARCHIVED" | "DOCUMENT_STATUS_DELETED";
            /** @description New tags (replaces existing) */
            tags?: {
                [key: string]: string;
            };
            /** @description Whether to update tags (if false, tags field is ignored) */
            updateTags?: boolean;
        };
        UpdateDocumentResponse: {
            document?: components["schemas"]["Document"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PaperlessCategoryService_ListCategories: {
        parameters: {
            query?: {
                /** @description Parent category ID (null for root-level categories) */
                parentId?: string;
                /** @description Pagination */
                page?: number;
                pageSize?: number;
                /** @description Search by name */
                nameFilter?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCategoriesResponse"];
                };
            };
        };
    };
    PaperlessCategoryService_CreateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCategoryResponse"];
                };
            };
        };
    };
    PaperlessCategoryService_GetCategoryTree: {
        parameters: {
            query?: {
                /** @description Root category ID (null for entire tree) */
                rootId?: string;
                /** @description Maximum depth to retrieve */
                maxDepth?: number;
                /** @description Include document counts */
                includeCounts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCategoryTreeResponse"];
                };
            };
        };
    };
    PaperlessCategoryService_GetCategory: {
        parameters: {
            query?: {
                /** @description Include document count */
                includeCounts?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCategoryResponse"];
                };
            };
        };
    };
    PaperlessCategoryService_UpdateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateCategoryResponse"];
                };
            };
        };
    };
    PaperlessCategoryService_DeleteCategory: {
        parameters: {
            query?: {
                /** @description Force delete even if category contains items */
                force?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaperlessCategoryService_MoveCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveCategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveCategoryResponse"];
                };
            };
        };
    };
    PaperlessDocumentService_ListDocuments: {
        parameters: {
            query?: {
                /** @description Category ID (null for root-level documents) */
                categoryId?: string;
                /** @description Pagination */
                page?: number;
                pageSize?: number;
                /** @description Filter by status */
                status?: "DOCUMENT_STATUS_UNSPECIFIED" | "DOCUMENT_STATUS_ACTIVE" | "DOCUMENT_STATUS_ARCHIVED" | "DOCUMENT_STATUS_DELETED";
                /** @description Filter by name */
                nameFilter?: string;
                /** @description Filter by MIME type */
                mimeTypeFilter?: string;
                /** @description Include subcategories */
                includeSubcategories?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDocumentsResponse"];
                };
            };
        };
    };
    PaperlessDocumentService_CreateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocumentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDocumentResponse"];
                };
            };
        };
    };
    PaperlessDocumentService_BatchDeleteDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeleteDocumentsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDeleteDocumentsResponse"];
                };
            };
        };
    };
    PaperlessDocumentService_SearchDocuments: {
        parameters: {
            query?: {
                /** @description Search query (searches name, description, file_name) */
                query?: string;
                /** @description Limit search to category and subcategories (null for all) */
                categoryId?: string;
                /** @description Include subcategories in search */
                includeSubcategories?: boolean;
                /** @description Pagination */
                page?: number;
                pageSize?: number;
                /** @description Filter by status */
                status?: "DOCUMENT_STATUS_UNSPECIFIED" | "DOCUMENT_STATUS_ACTIVE" | "DOCUMENT_STATUS_ARCHIVED" | "DOCUMENT_STATUS_DELETED";
                /** @description Filter by MIME type */
                mimeTypeFilter?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchDocumentsResponse"];
                };
            };
        };
    };
    PaperlessDocumentService_GetDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDocumentResponse"];
                };
            };
        };
    };
    PaperlessDocumentService_UpdateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDocumentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateDocumentResponse"];
                };
            };
        };
    };
    PaperlessDocumentService_DeleteDocument: {
        parameters: {
            query?: {
                /** @description Permanently delete (skip soft-delete and remove from storage) */
                permanent?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaperlessDocumentService_DownloadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadDocumentResponse"];
                };
            };
        };
    };
    PaperlessDocumentService_GetDocumentDownloadUrl: {
        parameters: {
            query?: {
                /** @description URL expiration in seconds (default 3600) */
                expiresIn?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDocumentDownloadUrlResponse"];
                };
            };
        };
    };
    PaperlessDocumentService_MoveDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveDocumentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveDocumentResponse"];
                };
            };
        };
    };
    PaperlessPermissionService_ListPermissions: {
        parameters: {
            query?: {
                /** @description Resource type (optional - filter by type) */
                resourceType?: "RESOURCE_TYPE_UNSPECIFIED" | "RESOURCE_TYPE_CATEGORY" | "RESOURCE_TYPE_DOCUMENT";
                /** @description Resource ID (optional - list for specific resource) */
                resourceId?: string;
                /** @description Subject type (optional - filter by subject type) */
                subjectType?: "SUBJECT_TYPE_UNSPECIFIED" | "SUBJECT_TYPE_USER" | "SUBJECT_TYPE_ROLE" | "SUBJECT_TYPE_TENANT";
                /** @description Subject ID (optional - list for specific subject) */
                subjectId?: string;
                /** @description Pagination */
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPermissionsResponse"];
                };
            };
        };
    };
    PaperlessPermissionService_GrantAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantAccessRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantAccessResponse"];
                };
            };
        };
    };
    PaperlessPermissionService_RevokeAccess: {
        parameters: {
            query?: {
                /** @description Resource type */
                resourceType?: "RESOURCE_TYPE_UNSPECIFIED" | "RESOURCE_TYPE_CATEGORY" | "RESOURCE_TYPE_DOCUMENT";
                /** @description Resource ID */
                resourceId?: string;
                /** @description Relation to revoke (optional - if not specified, revokes all) */
                relation?: "RELATION_UNSPECIFIED" | "RELATION_OWNER" | "RELATION_EDITOR" | "RELATION_VIEWER" | "RELATION_SHARER";
                /** @description Subject type */
                subjectType?: "SUBJECT_TYPE_UNSPECIFIED" | "SUBJECT_TYPE_USER" | "SUBJECT_TYPE_ROLE" | "SUBJECT_TYPE_TENANT";
                /** @description Subject ID */
                subjectId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaperlessPermissionService_ListAccessibleResources: {
        parameters: {
            query?: {
                /** @description User ID */
                userId?: string;
                /** @description Resource type to list */
                resourceType?: "RESOURCE_TYPE_UNSPECIFIED" | "RESOURCE_TYPE_CATEGORY" | "RESOURCE_TYPE_DOCUMENT";
                /** @description Minimum permission level */
                permission?: "PERMISSION_UNSPECIFIED" | "PERMISSION_READ" | "PERMISSION_WRITE" | "PERMISSION_DELETE" | "PERMISSION_SHARE" | "PERMISSION_DOWNLOAD";
                /** @description Pagination */
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAccessibleResourcesResponse"];
                };
            };
        };
    };
    PaperlessPermissionService_CheckAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckAccessRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckAccessResponse"];
                };
            };
        };
    };
    PaperlessPermissionService_GetEffectivePermissions: {
        parameters: {
            query?: {
                /** @description User ID */
                userId?: string;
                /** @description Resource type */
                resourceType?: "RESOURCE_TYPE_UNSPECIFIED" | "RESOURCE_TYPE_CATEGORY" | "RESOURCE_TYPE_DOCUMENT";
                /** @description Resource ID */
                resourceId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetEffectivePermissionsResponse"];
                };
            };
        };
    };
}
