// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PaperlessAuditLogsColumns holds the columns for the "paperless_audit_logs" table.
	PaperlessAuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "audit_id", Type: field.TypeString, Unique: true, Comment: "Unique audit log identifier (UUID)"},
		{Name: "request_id", Type: field.TypeString, Nullable: true, Comment: "Request ID from metadata"},
		{Name: "operation", Type: field.TypeString, Comment: "gRPC operation path"},
		{Name: "service_name", Type: field.TypeString, Comment: "Service name", Default: "paperless-service"},
		{Name: "client_id", Type: field.TypeString, Nullable: true, Comment: "Client ID from certificate CN"},
		{Name: "client_common_name", Type: field.TypeString, Nullable: true, Comment: "Client certificate common name"},
		{Name: "client_organization", Type: field.TypeString, Nullable: true, Comment: "Client certificate organization"},
		{Name: "client_serial_number", Type: field.TypeString, Nullable: true, Comment: "Client certificate serial number"},
		{Name: "is_authenticated", Type: field.TypeBool, Comment: "Whether the client was authenticated via mTLS", Default: false},
		{Name: "success", Type: field.TypeBool, Comment: "Whether the operation succeeded", Default: true},
		{Name: "error_code", Type: field.TypeInt32, Nullable: true, Comment: "Error code if failed"},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Comment: "Error message if failed"},
		{Name: "latency_ms", Type: field.TypeInt64, Comment: "Operation latency in milliseconds", Default: 0},
		{Name: "peer_address", Type: field.TypeString, Nullable: true, Comment: "Client IP address"},
		{Name: "geo_location", Type: field.TypeJSON, Nullable: true, Comment: "Geographic location info"},
		{Name: "log_hash", Type: field.TypeString, Nullable: true, Comment: "SHA-256 hash of the log content"},
		{Name: "signature", Type: field.TypeBytes, Nullable: true, Comment: "ECDSA signature for integrity verification"},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true, Comment: "Additional metadata"},
	}
	// PaperlessAuditLogsTable holds the schema information for the "paperless_audit_logs" table.
	PaperlessAuditLogsTable = &schema.Table{
		Name:       "paperless_audit_logs",
		Columns:    PaperlessAuditLogsColumns,
		PrimaryKey: []*schema.Column{PaperlessAuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paperless_auditlog_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessAuditLogsColumns[4]},
			},
			{
				Name:    "paperless_auditlog_tenant_client",
				Unique:  false,
				Columns: []*schema.Column{PaperlessAuditLogsColumns[4], PaperlessAuditLogsColumns[9]},
			},
			{
				Name:    "paperless_auditlog_tenant_operation",
				Unique:  false,
				Columns: []*schema.Column{PaperlessAuditLogsColumns[4], PaperlessAuditLogsColumns[7]},
			},
			{
				Name:    "paperless_auditlog_tenant_success",
				Unique:  false,
				Columns: []*schema.Column{PaperlessAuditLogsColumns[4], PaperlessAuditLogsColumns[14]},
			},
			{
				Name:    "paperless_auditlog_operation",
				Unique:  false,
				Columns: []*schema.Column{PaperlessAuditLogsColumns[7]},
			},
			{
				Name:    "paperless_auditlog_client_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessAuditLogsColumns[9]},
			},
			{
				Name:    "paperless_auditlog_success",
				Unique:  false,
				Columns: []*schema.Column{PaperlessAuditLogsColumns[14]},
			},
			{
				Name:    "paperless_auditlog_peer_address",
				Unique:  false,
				Columns: []*schema.Column{PaperlessAuditLogsColumns[18]},
			},
		},
	}
	// PaperlessCategoriesColumns holds the columns for the "paperless_categories" table.
	PaperlessCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Category name"},
		{Name: "path", Type: field.TypeString, Size: 4096, Comment: "Materialized path (e.g., /root/sub/current)"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 1024, Comment: "Optional description"},
		{Name: "depth", Type: field.TypeInt32, Comment: "Nesting depth level (0 for root categories)", Default: 0},
		{Name: "sort_order", Type: field.TypeInt32, Comment: "Sort order within parent (lower numbers appear first)", Default: 0},
		{Name: "parent_id", Type: field.TypeString, Nullable: true, Comment: "Parent category ID (null for root-level categories)"},
	}
	// PaperlessCategoriesTable holds the schema information for the "paperless_categories" table.
	PaperlessCategoriesTable = &schema.Table{
		Name:       "paperless_categories",
		Columns:    PaperlessCategoriesColumns,
		PrimaryKey: []*schema.Column{PaperlessCategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "paperless_categories_paperless_categories_children",
				Columns:    []*schema.Column{PaperlessCategoriesColumns[11]},
				RefColumns: []*schema.Column{PaperlessCategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "category_tenant_id_parent_id_name",
				Unique:  true,
				Columns: []*schema.Column{PaperlessCategoriesColumns[5], PaperlessCategoriesColumns[11], PaperlessCategoriesColumns[6]},
			},
			{
				Name:    "category_tenant_id_path",
				Unique:  true,
				Columns: []*schema.Column{PaperlessCategoriesColumns[5], PaperlessCategoriesColumns[7]},
			},
			{
				Name:    "category_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessCategoriesColumns[5]},
			},
			{
				Name:    "category_parent_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessCategoriesColumns[11]},
			},
			{
				Name:    "category_path",
				Unique:  false,
				Columns: []*schema.Column{PaperlessCategoriesColumns[7]},
			},
			{
				Name:    "category_tenant_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{PaperlessCategoriesColumns[5], PaperlessCategoriesColumns[10]},
			},
		},
	}
	// PaperlessDocumentsColumns holds the columns for the "paperless_documents" table.
	PaperlessDocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Document display name"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 4096, Comment: "Document description"},
		{Name: "file_key", Type: field.TypeString, Size: 512, Comment: "Storage key in RustFS/S3"},
		{Name: "file_name", Type: field.TypeString, Size: 255, Comment: "Original file name"},
		{Name: "file_size", Type: field.TypeInt64, Comment: "File size in bytes", Default: 0},
		{Name: "mime_type", Type: field.TypeString, Nullable: true, Size: 255, Comment: "MIME type of the file"},
		{Name: "checksum", Type: field.TypeString, Nullable: true, Size: 64, Comment: "SHA-256 checksum of the file"},
		{Name: "tags", Type: field.TypeJSON, Nullable: true, Comment: "Custom tags (key-value pairs)"},
		{Name: "status", Type: field.TypeEnum, Comment: "Document status", Enums: []string{"DOCUMENT_STATUS_UNSPECIFIED", "DOCUMENT_STATUS_ACTIVE", "DOCUMENT_STATUS_ARCHIVED", "DOCUMENT_STATUS_DELETED"}, Default: "DOCUMENT_STATUS_ACTIVE"},
		{Name: "source", Type: field.TypeEnum, Comment: "Source of the document (upload, email, etc.)", Enums: []string{"DOCUMENT_SOURCE_UNSPECIFIED", "DOCUMENT_SOURCE_UPLOAD", "DOCUMENT_SOURCE_EMAIL"}, Default: "DOCUMENT_SOURCE_UPLOAD"},
		{Name: "content_text", Type: field.TypeString, Nullable: true, Size: 2147483647, Comment: "Extracted text content for full-text search"},
		{Name: "extracted_metadata", Type: field.TypeJSON, Nullable: true, Comment: "Metadata extracted by Tika (author, title, page_count, etc.)"},
		{Name: "processing_status", Type: field.TypeEnum, Comment: "Document content extraction status", Enums: []string{"PROCESSING_STATUS_PENDING", "PROCESSING_STATUS_PROCESSING", "PROCESSING_STATUS_COMPLETED", "PROCESSING_STATUS_FAILED", "PROCESSING_STATUS_SKIPPED"}, Default: "PROCESSING_STATUS_PENDING"},
		{Name: "category_id", Type: field.TypeString, Nullable: true, Comment: "Parent category ID (null for root-level documents)"},
	}
	// PaperlessDocumentsTable holds the schema information for the "paperless_documents" table.
	PaperlessDocumentsTable = &schema.Table{
		Name:       "paperless_documents",
		Columns:    PaperlessDocumentsColumns,
		PrimaryKey: []*schema.Column{PaperlessDocumentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "paperless_documents_paperless_categories_documents",
				Columns:    []*schema.Column{PaperlessDocumentsColumns[20]},
				RefColumns: []*schema.Column{PaperlessCategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "document_tenant_id_category_id_name",
				Unique:  true,
				Columns: []*schema.Column{PaperlessDocumentsColumns[6], PaperlessDocumentsColumns[20], PaperlessDocumentsColumns[7]},
			},
			{
				Name:    "document_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessDocumentsColumns[6]},
			},
			{
				Name:    "document_category_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessDocumentsColumns[20]},
			},
			{
				Name:    "document_tenant_id_name",
				Unique:  false,
				Columns: []*schema.Column{PaperlessDocumentsColumns[6], PaperlessDocumentsColumns[7]},
			},
			{
				Name:    "document_status",
				Unique:  false,
				Columns: []*schema.Column{PaperlessDocumentsColumns[15]},
			},
			{
				Name:    "document_file_key",
				Unique:  true,
				Columns: []*schema.Column{PaperlessDocumentsColumns[9]},
			},
			{
				Name:    "document_tenant_id_mime_type",
				Unique:  false,
				Columns: []*schema.Column{PaperlessDocumentsColumns[6], PaperlessDocumentsColumns[12]},
			},
		},
	}
	// PaperlessPermissionsColumns holds the columns for the "paperless_permissions" table.
	PaperlessPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "resource_type", Type: field.TypeEnum, Comment: "Type of resource (category or document)", Enums: []string{"RESOURCE_TYPE_UNSPECIFIED", "RESOURCE_TYPE_CATEGORY", "RESOURCE_TYPE_DOCUMENT"}},
		{Name: "resource_id", Type: field.TypeString, Size: 36, Comment: "ID of the category or document"},
		{Name: "relation", Type: field.TypeEnum, Comment: "Permission level (owner, editor, viewer, sharer)", Enums: []string{"RELATION_UNSPECIFIED", "RELATION_OWNER", "RELATION_EDITOR", "RELATION_VIEWER", "RELATION_SHARER"}},
		{Name: "subject_type", Type: field.TypeEnum, Comment: "Type of subject (user, role, or tenant)", Enums: []string{"SUBJECT_TYPE_UNSPECIFIED", "SUBJECT_TYPE_USER", "SUBJECT_TYPE_ROLE", "SUBJECT_TYPE_TENANT"}},
		{Name: "subject_id", Type: field.TypeString, Size: 36, Comment: "ID of the user, role, or tenant"},
		{Name: "granted_by", Type: field.TypeUint32, Nullable: true, Comment: "User ID who granted this permission"},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, Comment: "Optional expiration time for temporary access"},
		{Name: "category_permissions", Type: field.TypeString, Nullable: true},
		{Name: "document_permissions", Type: field.TypeString, Nullable: true},
	}
	// PaperlessPermissionsTable holds the schema information for the "paperless_permissions" table.
	PaperlessPermissionsTable = &schema.Table{
		Name:       "paperless_permissions",
		Columns:    PaperlessPermissionsColumns,
		PrimaryKey: []*schema.Column{PaperlessPermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "paperless_permissions_paperless_categories_permissions",
				Columns:    []*schema.Column{PaperlessPermissionsColumns[12]},
				RefColumns: []*schema.Column{PaperlessCategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "paperless_permissions_paperless_documents_permissions",
				Columns:    []*schema.Column{PaperlessPermissionsColumns[13]},
				RefColumns: []*schema.Column{PaperlessDocumentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "documentpermission_tenant_id_resource_type_resource_id_relation_subject_type_subject_id",
				Unique:  true,
				Columns: []*schema.Column{PaperlessPermissionsColumns[4], PaperlessPermissionsColumns[5], PaperlessPermissionsColumns[6], PaperlessPermissionsColumns[7], PaperlessPermissionsColumns[8], PaperlessPermissionsColumns[9]},
			},
			{
				Name:    "documentpermission_tenant_id_resource_type_resource_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessPermissionsColumns[4], PaperlessPermissionsColumns[5], PaperlessPermissionsColumns[6]},
			},
			{
				Name:    "documentpermission_subject_type_subject_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessPermissionsColumns[8], PaperlessPermissionsColumns[9]},
			},
			{
				Name:    "documentpermission_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessPermissionsColumns[4]},
			},
			{
				Name:    "documentpermission_expires_at",
				Unique:  false,
				Columns: []*schema.Column{PaperlessPermissionsColumns[11]},
			},
		},
	}
	// PaperlessSigningRecipientsColumns holds the columns for the "paperless_signing_recipients" table.
	PaperlessSigningRecipientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "email", Type: field.TypeString, Size: 255, Comment: "Recipient email address"},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Recipient display name"},
		{Name: "signing_order", Type: field.TypeInt32, Comment: "Order in which recipients sign (1-based)", Default: 1},
		{Name: "status", Type: field.TypeEnum, Comment: "Recipient signing status", Enums: []string{"SIGNING_RECIPIENT_STATUS_UNSPECIFIED", "SIGNING_RECIPIENT_STATUS_WAITING", "SIGNING_RECIPIENT_STATUS_PENDING", "SIGNING_RECIPIENT_STATUS_COMPLETED", "SIGNING_RECIPIENT_STATUS_DECLINED"}, Default: "SIGNING_RECIPIENT_STATUS_WAITING"},
		{Name: "token", Type: field.TypeString, Unique: true, Size: 64, Comment: "Unique signing token (64-char hex)"},
		{Name: "signed_at", Type: field.TypeTime, Nullable: true, Comment: "Timestamp when recipient signed"},
		{Name: "signed_ip", Type: field.TypeString, Nullable: true, Size: 45, Comment: "IP address of signer"},
		{Name: "signature_data", Type: field.TypeBytes, Nullable: true, Comment: "Signature image data (PNG)"},
		{Name: "signing_request_id", Type: field.TypeString, Comment: "Reference to signing request"},
	}
	// PaperlessSigningRecipientsTable holds the schema information for the "paperless_signing_recipients" table.
	PaperlessSigningRecipientsTable = &schema.Table{
		Name:       "paperless_signing_recipients",
		Columns:    PaperlessSigningRecipientsColumns,
		PrimaryKey: []*schema.Column{PaperlessSigningRecipientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "paperless_signing_recipients_paperless_signing_requests_recipients",
				Columns:    []*schema.Column{PaperlessSigningRecipientsColumns[12]},
				RefColumns: []*schema.Column{PaperlessSigningRequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "signingrecipient_token",
				Unique:  true,
				Columns: []*schema.Column{PaperlessSigningRecipientsColumns[8]},
			},
			{
				Name:    "signingrecipient_signing_request_id_signing_order",
				Unique:  false,
				Columns: []*schema.Column{PaperlessSigningRecipientsColumns[12], PaperlessSigningRecipientsColumns[6]},
			},
			{
				Name:    "signingrecipient_signing_request_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessSigningRecipientsColumns[12]},
			},
		},
	}
	// PaperlessSigningRequestsColumns holds the columns for the "paperless_signing_requests" table.
	PaperlessSigningRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "template_id", Type: field.TypeString, Size: 36, Comment: "Reference to signing template"},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Request display name"},
		{Name: "status", Type: field.TypeEnum, Comment: "Request status", Enums: []string{"SIGNING_REQUEST_STATUS_UNSPECIFIED", "SIGNING_REQUEST_STATUS_DRAFT", "SIGNING_REQUEST_STATUS_PENDING", "SIGNING_REQUEST_STATUS_COMPLETED", "SIGNING_REQUEST_STATUS_CANCELLED", "SIGNING_REQUEST_STATUS_EXPIRED"}, Default: "SIGNING_REQUEST_STATUS_DRAFT"},
		{Name: "original_file_key", Type: field.TypeString, Nullable: true, Size: 512, Comment: "Storage key for the original PDF copy"},
		{Name: "signed_file_key", Type: field.TypeString, Nullable: true, Size: 512, Comment: "Storage key for the signed/completed PDF"},
		{Name: "field_values", Type: field.TypeJSON, Nullable: true, Comment: "Filled field values from all signers"},
		{Name: "message", Type: field.TypeString, Nullable: true, Size: 4096, Comment: "Custom message to recipients"},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, Comment: "Expiration time for the signing request"},
	}
	// PaperlessSigningRequestsTable holds the schema information for the "paperless_signing_requests" table.
	PaperlessSigningRequestsTable = &schema.Table{
		Name:       "paperless_signing_requests",
		Columns:    PaperlessSigningRequestsColumns,
		PrimaryKey: []*schema.Column{PaperlessSigningRequestsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "signingrequest_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessSigningRequestsColumns[6]},
			},
			{
				Name:    "signingrequest_status",
				Unique:  false,
				Columns: []*schema.Column{PaperlessSigningRequestsColumns[9]},
			},
			{
				Name:    "signingrequest_template_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessSigningRequestsColumns[7]},
			},
			{
				Name:    "signingrequest_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{PaperlessSigningRequestsColumns[6], PaperlessSigningRequestsColumns[9]},
			},
		},
	}
	// PaperlessSigningTemplatesColumns holds the columns for the "paperless_signing_templates" table.
	PaperlessSigningTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Template display name"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 4096, Comment: "Template description"},
		{Name: "file_key", Type: field.TypeString, Size: 512, Comment: "Storage key in RustFS/S3"},
		{Name: "file_name", Type: field.TypeString, Size: 255, Comment: "Original file name"},
		{Name: "file_size", Type: field.TypeInt64, Comment: "File size in bytes", Default: 0},
		{Name: "fields", Type: field.TypeJSON, Nullable: true, Comment: "Parsed placeholder field definitions"},
	}
	// PaperlessSigningTemplatesTable holds the schema information for the "paperless_signing_templates" table.
	PaperlessSigningTemplatesTable = &schema.Table{
		Name:       "paperless_signing_templates",
		Columns:    PaperlessSigningTemplatesColumns,
		PrimaryKey: []*schema.Column{PaperlessSigningTemplatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "signingtemplate_tenant_id_name",
				Unique:  true,
				Columns: []*schema.Column{PaperlessSigningTemplatesColumns[6], PaperlessSigningTemplatesColumns[7]},
			},
			{
				Name:    "signingtemplate_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{PaperlessSigningTemplatesColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PaperlessAuditLogsTable,
		PaperlessCategoriesTable,
		PaperlessDocumentsTable,
		PaperlessPermissionsTable,
		PaperlessSigningRecipientsTable,
		PaperlessSigningRequestsTable,
		PaperlessSigningTemplatesTable,
	}
)

func init() {
	PaperlessAuditLogsTable.Annotation = &entsql.Annotation{
		Table: "paperless_audit_logs",
	}
	PaperlessCategoriesTable.ForeignKeys[0].RefTable = PaperlessCategoriesTable
	PaperlessCategoriesTable.Annotation = &entsql.Annotation{
		Table: "paperless_categories",
	}
	PaperlessDocumentsTable.ForeignKeys[0].RefTable = PaperlessCategoriesTable
	PaperlessDocumentsTable.Annotation = &entsql.Annotation{
		Table: "paperless_documents",
	}
	PaperlessPermissionsTable.ForeignKeys[0].RefTable = PaperlessCategoriesTable
	PaperlessPermissionsTable.ForeignKeys[1].RefTable = PaperlessDocumentsTable
	PaperlessPermissionsTable.Annotation = &entsql.Annotation{
		Table: "paperless_permissions",
	}
	PaperlessSigningRecipientsTable.ForeignKeys[0].RefTable = PaperlessSigningRequestsTable
	PaperlessSigningRecipientsTable.Annotation = &entsql.Annotation{
		Table: "paperless_signing_recipients",
	}
	PaperlessSigningRequestsTable.Annotation = &entsql.Annotation{
		Table: "paperless_signing_requests",
	}
	PaperlessSigningTemplatesTable.Annotation = &entsql.Annotation{
		Table: "paperless_signing_templates",
	}
}
