// Code generated by ent, DO NOT EDIT.

package signingrecipient

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/go-tangra/go-tangra-paperless/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldDeleteTime, v))
}

// SigningRequestID applies equality check predicate on the "signing_request_id" field. It's identical to SigningRequestIDEQ.
func SigningRequestID(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldSigningRequestID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldEmail, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldName, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldUserID, v))
}

// SigningOrder applies equality check predicate on the "signing_order" field. It's identical to SigningOrderEQ.
func SigningOrder(v int32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldSigningOrder, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldToken, v))
}

// SignedAt applies equality check predicate on the "signed_at" field. It's identical to SignedAtEQ.
func SignedAt(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldSignedAt, v))
}

// SignedIP applies equality check predicate on the "signed_ip" field. It's identical to SignedIPEQ.
func SignedIP(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldSignedIP, v))
}

// SignatureData applies equality check predicate on the "signature_data" field. It's identical to SignatureDataEQ.
func SignatureData(v []byte) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldSignatureData, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotNull(FieldDeleteTime))
}

// SigningRequestIDEQ applies the EQ predicate on the "signing_request_id" field.
func SigningRequestIDEQ(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldSigningRequestID, v))
}

// SigningRequestIDNEQ applies the NEQ predicate on the "signing_request_id" field.
func SigningRequestIDNEQ(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldSigningRequestID, v))
}

// SigningRequestIDIn applies the In predicate on the "signing_request_id" field.
func SigningRequestIDIn(vs ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldSigningRequestID, vs...))
}

// SigningRequestIDNotIn applies the NotIn predicate on the "signing_request_id" field.
func SigningRequestIDNotIn(vs ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldSigningRequestID, vs...))
}

// SigningRequestIDGT applies the GT predicate on the "signing_request_id" field.
func SigningRequestIDGT(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldSigningRequestID, v))
}

// SigningRequestIDGTE applies the GTE predicate on the "signing_request_id" field.
func SigningRequestIDGTE(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldSigningRequestID, v))
}

// SigningRequestIDLT applies the LT predicate on the "signing_request_id" field.
func SigningRequestIDLT(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldSigningRequestID, v))
}

// SigningRequestIDLTE applies the LTE predicate on the "signing_request_id" field.
func SigningRequestIDLTE(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldSigningRequestID, v))
}

// SigningRequestIDContains applies the Contains predicate on the "signing_request_id" field.
func SigningRequestIDContains(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldContains(FieldSigningRequestID, v))
}

// SigningRequestIDHasPrefix applies the HasPrefix predicate on the "signing_request_id" field.
func SigningRequestIDHasPrefix(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldHasPrefix(FieldSigningRequestID, v))
}

// SigningRequestIDHasSuffix applies the HasSuffix predicate on the "signing_request_id" field.
func SigningRequestIDHasSuffix(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldHasSuffix(FieldSigningRequestID, v))
}

// SigningRequestIDEqualFold applies the EqualFold predicate on the "signing_request_id" field.
func SigningRequestIDEqualFold(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEqualFold(FieldSigningRequestID, v))
}

// SigningRequestIDContainsFold applies the ContainsFold predicate on the "signing_request_id" field.
func SigningRequestIDContainsFold(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldContainsFold(FieldSigningRequestID, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldContainsFold(FieldEmail, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldContainsFold(FieldName, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotNull(FieldUserID))
}

// SigningOrderEQ applies the EQ predicate on the "signing_order" field.
func SigningOrderEQ(v int32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldSigningOrder, v))
}

// SigningOrderNEQ applies the NEQ predicate on the "signing_order" field.
func SigningOrderNEQ(v int32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldSigningOrder, v))
}

// SigningOrderIn applies the In predicate on the "signing_order" field.
func SigningOrderIn(vs ...int32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldSigningOrder, vs...))
}

// SigningOrderNotIn applies the NotIn predicate on the "signing_order" field.
func SigningOrderNotIn(vs ...int32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldSigningOrder, vs...))
}

// SigningOrderGT applies the GT predicate on the "signing_order" field.
func SigningOrderGT(v int32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldSigningOrder, v))
}

// SigningOrderGTE applies the GTE predicate on the "signing_order" field.
func SigningOrderGTE(v int32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldSigningOrder, v))
}

// SigningOrderLT applies the LT predicate on the "signing_order" field.
func SigningOrderLT(v int32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldSigningOrder, v))
}

// SigningOrderLTE applies the LTE predicate on the "signing_order" field.
func SigningOrderLTE(v int32) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldSigningOrder, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldStatus, vs...))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldContainsFold(FieldToken, v))
}

// SignedAtEQ applies the EQ predicate on the "signed_at" field.
func SignedAtEQ(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldSignedAt, v))
}

// SignedAtNEQ applies the NEQ predicate on the "signed_at" field.
func SignedAtNEQ(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldSignedAt, v))
}

// SignedAtIn applies the In predicate on the "signed_at" field.
func SignedAtIn(vs ...time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldSignedAt, vs...))
}

// SignedAtNotIn applies the NotIn predicate on the "signed_at" field.
func SignedAtNotIn(vs ...time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldSignedAt, vs...))
}

// SignedAtGT applies the GT predicate on the "signed_at" field.
func SignedAtGT(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldSignedAt, v))
}

// SignedAtGTE applies the GTE predicate on the "signed_at" field.
func SignedAtGTE(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldSignedAt, v))
}

// SignedAtLT applies the LT predicate on the "signed_at" field.
func SignedAtLT(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldSignedAt, v))
}

// SignedAtLTE applies the LTE predicate on the "signed_at" field.
func SignedAtLTE(v time.Time) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldSignedAt, v))
}

// SignedAtIsNil applies the IsNil predicate on the "signed_at" field.
func SignedAtIsNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIsNull(FieldSignedAt))
}

// SignedAtNotNil applies the NotNil predicate on the "signed_at" field.
func SignedAtNotNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotNull(FieldSignedAt))
}

// SignedIPEQ applies the EQ predicate on the "signed_ip" field.
func SignedIPEQ(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldSignedIP, v))
}

// SignedIPNEQ applies the NEQ predicate on the "signed_ip" field.
func SignedIPNEQ(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldSignedIP, v))
}

// SignedIPIn applies the In predicate on the "signed_ip" field.
func SignedIPIn(vs ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldSignedIP, vs...))
}

// SignedIPNotIn applies the NotIn predicate on the "signed_ip" field.
func SignedIPNotIn(vs ...string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldSignedIP, vs...))
}

// SignedIPGT applies the GT predicate on the "signed_ip" field.
func SignedIPGT(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldSignedIP, v))
}

// SignedIPGTE applies the GTE predicate on the "signed_ip" field.
func SignedIPGTE(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldSignedIP, v))
}

// SignedIPLT applies the LT predicate on the "signed_ip" field.
func SignedIPLT(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldSignedIP, v))
}

// SignedIPLTE applies the LTE predicate on the "signed_ip" field.
func SignedIPLTE(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldSignedIP, v))
}

// SignedIPContains applies the Contains predicate on the "signed_ip" field.
func SignedIPContains(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldContains(FieldSignedIP, v))
}

// SignedIPHasPrefix applies the HasPrefix predicate on the "signed_ip" field.
func SignedIPHasPrefix(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldHasPrefix(FieldSignedIP, v))
}

// SignedIPHasSuffix applies the HasSuffix predicate on the "signed_ip" field.
func SignedIPHasSuffix(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldHasSuffix(FieldSignedIP, v))
}

// SignedIPIsNil applies the IsNil predicate on the "signed_ip" field.
func SignedIPIsNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIsNull(FieldSignedIP))
}

// SignedIPNotNil applies the NotNil predicate on the "signed_ip" field.
func SignedIPNotNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotNull(FieldSignedIP))
}

// SignedIPEqualFold applies the EqualFold predicate on the "signed_ip" field.
func SignedIPEqualFold(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEqualFold(FieldSignedIP, v))
}

// SignedIPContainsFold applies the ContainsFold predicate on the "signed_ip" field.
func SignedIPContainsFold(v string) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldContainsFold(FieldSignedIP, v))
}

// SignatureDataEQ applies the EQ predicate on the "signature_data" field.
func SignatureDataEQ(v []byte) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldEQ(FieldSignatureData, v))
}

// SignatureDataNEQ applies the NEQ predicate on the "signature_data" field.
func SignatureDataNEQ(v []byte) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNEQ(FieldSignatureData, v))
}

// SignatureDataIn applies the In predicate on the "signature_data" field.
func SignatureDataIn(vs ...[]byte) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIn(FieldSignatureData, vs...))
}

// SignatureDataNotIn applies the NotIn predicate on the "signature_data" field.
func SignatureDataNotIn(vs ...[]byte) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotIn(FieldSignatureData, vs...))
}

// SignatureDataGT applies the GT predicate on the "signature_data" field.
func SignatureDataGT(v []byte) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGT(FieldSignatureData, v))
}

// SignatureDataGTE applies the GTE predicate on the "signature_data" field.
func SignatureDataGTE(v []byte) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldGTE(FieldSignatureData, v))
}

// SignatureDataLT applies the LT predicate on the "signature_data" field.
func SignatureDataLT(v []byte) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLT(FieldSignatureData, v))
}

// SignatureDataLTE applies the LTE predicate on the "signature_data" field.
func SignatureDataLTE(v []byte) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldLTE(FieldSignatureData, v))
}

// SignatureDataIsNil applies the IsNil predicate on the "signature_data" field.
func SignatureDataIsNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldIsNull(FieldSignatureData))
}

// SignatureDataNotNil applies the NotNil predicate on the "signature_data" field.
func SignatureDataNotNil() predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.FieldNotNull(FieldSignatureData))
}

// HasSigningRequest applies the HasEdge predicate on the "signing_request" edge.
func HasSigningRequest() predicate.SigningRecipient {
	return predicate.SigningRecipient(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SigningRequestTable, SigningRequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSigningRequestWith applies the HasEdge predicate on the "signing_request" edge with a given conditions (other predicates).
func HasSigningRequestWith(preds ...predicate.SigningRequest) predicate.SigningRecipient {
	return predicate.SigningRecipient(func(s *sql.Selector) {
		step := newSigningRequestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SigningRecipient) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SigningRecipient) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SigningRecipient) predicate.SigningRecipient {
	return predicate.SigningRecipient(sql.NotPredicates(p))
}
