// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-paperless/internal/cert"
	"github.com/go-tangra/go-tangra-paperless/internal/data"
	"github.com/go-tangra/go-tangra-paperless/internal/server"
	"github.com/go-tangra/go-tangra-paperless/internal/service"
	"github.com/go-tangra/go-tangra-paperless/internal/service/providers"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	auditLogRepo := data.NewAuditLogRepo(context, entClient)
	categoryRepo := data.NewCategoryRepo(context, entClient)
	permissionRepo := data.NewPermissionRepo(context, entClient)
	permissionStore := providers.ProvidePermissionStore(permissionRepo)
	documentRepo := data.NewDocumentRepo(context, entClient, categoryRepo)
	resourceLookup := providers.ProvideResourceLookup(categoryRepo, documentRepo)
	engine := providers.ProvideAuthzEngine(permissionStore, resourceLookup, context)
	checker := providers.ProvideAuthzChecker(engine)
	categoryService := service.NewCategoryService(context, categoryRepo, permissionRepo, checker)
	storageClient, cleanup2, err := data.NewStorageClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tikaClient, cleanup3, err := data.NewTikaClient(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	gotenbergClient, cleanup4, err := data.NewGotenbergClient(context)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	documentProcessor := service.NewDocumentProcessor(context, tikaClient, gotenbergClient, documentRepo)
	documentService := service.NewDocumentService(context, documentRepo, categoryRepo, permissionRepo, storageClient, documentProcessor, checker)
	permissionService := service.NewPermissionService(context, permissionRepo, engine)
	statisticsRepo := data.NewStatisticsRepo(context, entClient)
	statisticsService := service.NewStatisticsService(context, statisticsRepo)
	backupService := service.NewBackupService(context, entClient)
	grpcServer := server.NewGRPCServer(context, certManager, auditLogRepo, categoryService, documentService, permissionService, statisticsService, backupService)
	app := newApp(context, grpcServer)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
